### ISSUE TITLE
Light Projection on Wall

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#11]
### Description:
On level 4's Big Space, we will have a light projection design on to the wall.

### Previous Applications
Reference last year's applications https://github.com/MozillaFoundation/Mozfest2016_production/issues/188#issuecomment-258993050

### Blockers: 
2017 visual direction

### Reference from Last Year: 
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/188
![mozfest-logo-wall-projection small](https://cloud.githubusercontent.com/assets/2492510/20079232/a1f511b8-a4f8-11e6-8166-2813613cbcb2.gif)
__________________________
#### Deadline
GanttStart: 2017-09-04
GanttDue: 2017-09-06

**Comment by sabrinang** [comment]
@EsmeSimcox Do you know what colours are available and are we limited to one? (example: can we switch between tagline and gear logo)

**Comment by EsmeSimcox** [comment]
@sabrinang Do you know what you used last year to create this? Was it a project or something else?

**Comment by marcwalsh** [comment]
@sabrinang - We just need an RGB value for the colour, as it's full spectrum. I'll double check but it should be possible to cycle through more than one.

**Comment by sabrinang** [comment]
This will be the cog again this year

**Comment by sabrinang** [comment]
Please use this blue: RGB 4, 51, 255
Here is the .svg for the gear: https://drive.google.com/file/d/0B4Q8pzCpDS_edDNXMXdORXAwWm8/view?usp=sharing

**Comment by marcwalsh** [comment]
Sent to print!

**Comment by sabrinang** [comment]
## Post Mozfest Documentation

see issue #83
