### ISSUE TITLE
Slides: Speaker Intro/Outro Screens + Speaker Template

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#12]
### Description:
Update the slides that come before and after speaker's own slides with new visuals in various colour themes. Slides to consider to design:
- Speaker Series Section Intros
- 5 IH issue areas
- Speaker bio
- Title of talk
- Logo slide
- Q&A
- Thank You

Update a template for speaker's to use with their own slide content if they do not already have their own.

### Previous Applications
Last year's speaker series applications: https://github.com/MozillaFoundation/Mozfest2016_production/issues/87#issuecomment-259005198
Last year's keynote applications: https://github.com/MozillaFoundation/Mozfest2016_production/issues/86#issuecomment-259009788

### Blockers: 
2017 visual direction

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLU0d0VU5uQWJNbWM
Intro + Bookend GSlides: https://docs.google.com/presentation/d/1ztrY9GBVc10nSUFFXxE1d0UZZDRNRhCAZ9-cUfz60a0/edit?usp=sharing
Speaker's Template: https://docs.google.com/presentation/d/1LxSvUaG5BTq8Zv4os_Qmgkgb204LiXWM3RoABVE-bxE/edit?usp=sharing
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/86 & https://github.com/MozillaFoundation/Mozfest2016_production/issues/87

__________________________
#### Deadline
GanttStart: 2017-09-18
GanttDue: 2017-09-29

**Comment by sabrinang** [comment]
Slides to make:
- Intro slide - Dialogues and Debates title with time block
- Speaker bio slide - Name, Role, Twitter handle
- Thank you slide
- 2 Blank slides - 1 Coloured, 1 White
- Tagline slide - Web for All
- Gear slide

We can tie this into the Dialogues and Debates designs seen on the from https://github.com/MozillaFoundation/mozfest-design-2017/issues/43 festival guide + https://github.com/MozillaFoundation/mozfest-design-2017/issues/37 posters (for intro slides with red/blue title time blocks) and we can also build off from https://github.com/MozillaFoundation/mozfest-design-2017/issues/55 social profile cards for speaker bio slides.

@edrushka Regarding content,  do you know if...
this year are the talks related to specific spaces? 
we know the title of the talks?
we need a Q&A slide? (unsure if this was used last year)

**Comment by edrushka** [comment]
@KevZawacki can you help Sabrina with this one, please.

**Comment by KevZawacki** [comment]
Hi @sabrinang,

Talks are not explicitly linked to spaces / issues.

Some speakers have shared talk titles, some have not. For consistency, let's not include titles on our slides; speakers will likely have titles on their own slides, anyway.

Yep, let's do a Q&A slide.

Let me know if I can answer more questions.

**Comment by taisdesouzalessa** [comment]
@sabrinang here are the slides. Please take a look and let me know if you have any feedback:
https://docs.google.com/a/mozilla.com/presentation/d/1mpZinScsuF8Lnjfik600ZBnjnGuGHWPt60if543o4B0/edit?usp=sharing

@KevZawacki @edrushka could you please take a look at the content and check if it is all good? Also, let me know if you have any feedback as well.

**Comment by KevZawacki** [comment]
@taisdesouzalessa These look great! No changes from me.

**Comment by edrushka** [comment]
Question @KevZawacki - do we want Mark, Katherine and Ryan combined on one slide? Or do we want all three individually and we'll try to rotate through them? (Not sure if we can even do that)

**Comment by KevZawacki** [comment]
@edrushka Either works for me — whichever is easiest for design & a/v.

**Comment by taisdesouzalessa** [comment]
I can design them combined in 1 slide and you can choose which one to use, how about that? I imagine it would be difficult to rotate if they are individual ones.

**Comment by edrushka** [comment]
Thanks - that would be perfect.

**Comment by taisdesouzalessa** [comment]
@edrushka @KevZawacki I updated the slide deck:
https://docs.google.com/a/mozilla.com/presentation/d/1mpZinScsuF8Lnjfik600ZBnjnGuGHWPt60if543o4B0/edit?usp=sharing

Slides 11, 12 and 13 are individual pictures. Slide 14 is all of 3 pictures together. You can use either one, depending on the presentation needs. Let me know if it works.

@sabrinang FYI - slide 14 is new :).

**Comment by sabrinang** [comment]
👍 Thanks for combining @taisdesouzalessa - looking good!

**Comment by sabrinang** [comment]
## Post MozFest Documentation
These slides were fantastic and were used inbetween to display time blocks. These backgrounds were made to match the stage but the stages weren't switched:
![mozilla-festival-2017-206](https://user-images.githubusercontent.com/2492510/33224353-85e1ea76-d11d-11e7-8679-e1d3a13ebcd4.jpg)
There was some typography issues happening for slides and some were created last minute by the airmo team:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/2492510/33224116-e59f2346-d11a-11e7-94ea-8d3f0cfff0c7.png">
The speaker intro slides were seen occasionally but the typeface was off as well. Other times the speaker slide and live transcription was seen instead.
![dsc00237](https://user-images.githubusercontent.com/2492510/33224379-d04a5742-d11d-11e7-91fd-4ebda31699d5.JPG)
![img_20171029_112810](https://user-images.githubusercontent.com/4515662/33224490-b143ba18-d11e-11e7-888c-d052eff42f2a.jpg)

The speaker intro slides could of been displayed on airmo too.
