### ISSUE TITLE
Screen: Background + Assets for ProPresenter Social

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#14]
### Description:
Some screens will be using ProPresenter to showcase social media activity from twitter, instagram etc.

Assets TBD to deliver:
- background
- typography
- lockups
- tagline
- hashtag

### Previous Applications:
https://github.com/MozillaFoundation/Mozfest2016_production/issues/214#issuecomment-259269432

### Blockers: 
- 2017 style guide

### Deliver to:
- stage crew 

### Reference from Last Year: 
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/214

__________________________
#### Deadline
GanttStart: 2017-10-02
GanttDue: 2017-10-04

**Comment by sabrinang** [comment]
@edrushka Do you have specific asset list for ProPresenter (dimensions, file formats, type files)?

**Comment by edrushka** [comment]
Here's what Mac told us last year: 

> "We need background in original artwork. Not or original vector art of logo. Any #'s in approved font as png or original vector art. "

Here's what last year's slide looked like when all the elements were combined. Note that we need to include sponsor slides on this pre-reel.

<img width="1920" alt="propresenter-slide-ailerons" src="https://user-images.githubusercontent.com/4515662/31827857-96bd11fa-b5b0-11e7-96e9-7d0f3ac7293a.png">

**Comment by sabrinang** [comment]
![mozilla-festival-2017_propresenter-slide](https://user-images.githubusercontent.com/2492510/31857907-fc7ad4f2-b69e-11e7-8b6a-e43c91b7e040.jpg)
Assets are in gdrive: https://drive.google.com/open?id=0B4Q8pzCpDS_ea3NxRUZ5R3VXZFk

**Comment by edrushka** [comment]
@marcwalsh can you or Mac test this on Propresenter ahead of Saturday morning?

**Comment by sabrinang** [comment]
Assets and .jpgs are here: https://drive.google.com/open?id=0B4Q8pzCpDS_ea3NxRUZ5R3VXZFk

**Comment by sabrinang** [comment]
## Post MozFest Documentation
During opening talk, sponsor logos were seen. The black bar title style matches the sponsor banner so these worked well
![mozilla-festival-2017-123](https://user-images.githubusercontent.com/2492510/33223905-26386180-d119-11e7-955c-36e2edca07f7.jpg)
![mozilla-festival-2017-128](https://user-images.githubusercontent.com/2492510/33223908-2c4d7e16-d119-11e7-8b3a-05f9d4442bb7.jpg)

Tweet selector was quite a pain. Kept losing wifi and stalling on one image. If tweets didn't have a photo attached, it showed a wierd icon.
Tweet with no image attached:
![img_20171028_124253](https://user-images.githubusercontent.com/4515662/33223927-6ad6d326-d119-11e7-93ef-954fc76e3c94.jpg)

**Comment by edrushka** [comment]
Fro 2018, try to use the proper MozFest font and not the propresenter default font.
