### ISSUE TITLE
Screen: Background + Assets for AirMo + Facebook Stream

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#15]
### Description:
For audiences tuning into the speaker series on Air Mozilla or Facebook, we need to prepare some branded assets to be displayed with the video stream.

Assets TBD to deliver:
- Background behind AirMo Logo (16x9, 1920x1080)
- Lockup, Logo + Wordmark (.png)
- Title Card for MozFest 2017 Opening Keynote (16:9, 1920x1080)
- Title Card for MozFest 2017 Speaker Series (16:9, 1920x1080)

### Blockers: 
- 2017 style guide

### Reference from Last Year: 
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/206
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLaTJidS1zbzBVamM
__________________________
#### Deadline
GanttStart: 2017-10-04
GanttDue: 2017-10-06

**Comment by sabrinang** [comment]
@edrushka Can you confirm if the list above is the asset list we need for this years air.mo and facebook streams?

**Comment by edrushka** [comment]
I don't believe we are adding anything new this year, so if that list is the same as last year we should be good.

cc-ing @KevZawacki and @marcwalsh in case there are additions I'm not aware of.

**Comment by KevZawacki** [comment]
@edrushka, nothing new of which I'm aware.

**Comment by sabrinang** [comment]
@edrushka Please review content of title cards redpen here: https://redpen.io/p/md7629c158fcf0d629

**Comment by edrushka** [comment]
✅   R+ on **background only** 

🔺  **Opening title card:**
- we'll have three speakers on Saturday:
- Solana Larsen
- Femi Owolade-Coombes
- Gunner
- Mark Surman (not scheduled, but better make him card just in case)
Suggest you remove "opening keynote" and title/org and just have their names in large font

🔺  **D&D cards**
- Please make the background like the opening title card, with large font text that says "Dialogues and Debates" (no photos)

**Comment by sabrinang** [comment]
@edrushka I revised the [redpen](https://redpen.io/p/md7629c158fcf0d629) with stages in mind (now reversed) using blue-red for main and teals for D&D since they will be in view when streamed - Is that ok having two bg colours?

**Comment by edrushka** [comment]
Very nice! Works for me if it works for the AV team.

**Comment by edrushka** [comment]
@marcwalsh can you share these w/the AirMo team and Mac to make sure they're ok?

**Comment by sabrinang** [comment]
.JPGs and assets are here: https://drive.google.com/open?id=0B4Q8pzCpDS_eZGZwMW94ZFd4dkk

**Comment by edrushka** [comment]
Thank you. I've shared w/Andy from AirMo and Mac from AV.

**Comment by edrushka** [comment]
@sabrinang can you kindly make a holding slide for the plenary that says Welcome to MozFest (or if that's too long, then Opening Plenary). This will be the holding image on AirMo before the stream begins. Please email it to akochendorfer@mozilla.com and cc me. Thank you!

**Comment by sabrinang** [comment]
@edrushka Email sent and I updated jpg folder: https://drive.google.com/open?id=0B4Q8pzCpDS_eVkRFT2pKMVUxTnM
<img width="997" alt="screen shot 2017-10-28 at 5 52 54 am" src="https://user-images.githubusercontent.com/2492510/32131371-56706d32-bba4-11e7-80f6-7d776295a606.png">

**Comment by sabrinang** [comment]
## Post MozFest Documentation
The title slides were used for the thumbnails
<img width="631" alt="image" src="https://user-images.githubusercontent.com/2492510/33224162-6097b8ce-d11b-11e7-9151-964353c5cc7c.png">
The name slides were not used at all since the live transcription was on both screens. Next year, use name slide for an introduction and use it on the other. Also the name slides could of been displayed on air mozilla/facebook live. Overall, I think the live transcription was really busy visually and a bit overwhelming:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/2492510/33224238-1457de20-d11c-11e7-98f6-83e0450ac1bf.png">
A timestamp was displayed on airmozilla videos as well
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/2492510/33224120-fa0fa396-d11a-11e7-8e4d-18a3b48b7de0.png">
