### ISSUE TITLE
Comms: Email Banner

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2017#16]
Hey @sabrinang 

We're looking to send a mail out early next week to let everyone know that the tickets are on sale.

Does a generic banner exist already for emails, similar to the Call for Proposals one?

🎟🎟🎟🎟🎟🎟

**Comment by sabrinang** [comment]
There is no generic one yet _(the previous call for proposals had specific text on it)_. 

Is this email sent out on Aug 2? and to clarify you do not want any text on this banner? 
Also, if there is any specific banner dimensions let me know.

**Comment by marcwalsh** [comment]
It would be the same dimensions as the call for proposals. No text is needed just the same as the Call for Proposals with the text removed if possible. 

It was meant to be for 1st August to send to those who have subscribed for updated on ti.to, as well as just having something generic for us to send in case there is anything last minute that pops up.

**Comment by sabrinang** [comment]
Generic banners exported here: https://drive.google.com/open?id=0B4Q8pzCpDS_eU0ZyMnA3OGtHNWM
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/2492510/28804524-9ac73456-7618-11e7-81a9-9846ebf687ce.png">

**Comment by marcwalsh** [comment]
❤️  - Looking awesome!!! 

Thanks @sabrinang
