### ISSUE TITLE
Master Wayfinding List and Concept

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#17]
### Description

Master ticket to consider the wayfinding system concept and to build from the wayfinding work we established last year and explore different concepts.

Referring to last year’s way finding, here are some examples:
- Wayfinding: Space Banners
- Wayfinding: Floor plans maps
- Wayfinding: Floor vinyl
- Wayfinding: Registration table banner
- Sign: MozFest banner
- Sign: Registration / Sign-in
- Sign: Welcome
- Sign: Swag
- Sign: Customize Name Tag
- Sign: Youth & Press 
- Sign: Info booth
- Sign: #MozHelp desk
- Hackable Signs: Sessions
- Hackable Cards: Demos

This year we can also consider some more ideas inspired by stickers (tbd) and inspiration from the ravensbourne grad show (https://github.com/mozilla/mozillafestival.org/issues/659)

We can use this ticket to brainstorm and establish ideas before we turn this into an epic and file corresponding issues for each way finding piece.

### Dependencies
Finalized wayfinding ideas

### Reference from Previous Years:

* Concept/Master https://github.com/MozillaFoundation/Mozfest2016_production/issues/131
* Floor vinyl and internal signage https://github.com/MozillaFoundation/Mozfest2016_production/issues/89
* Floor plan maps https://github.com/MozillaFoundation/Mozfest2016_production/issues/91
* Space banners https://github.com/MozillaFoundation/Mozfest2016_production/issues/102
* Info booths https://github.com/MozillaFoundation/Mozfest2016_production/issues/90
* session signage https://github.com/MozillaFoundation/Mozfest2016_production/issues/92
* science fair and closing demo info cards https://github.com/MozillaFoundation/Mozfest2016_production/issues/94

**Comment by sabrinang** [comment]
Yesterday I chatted with @EsmeSimcox and she linked to degree show wayfinding examples: https://docs.google.com/presentation/d/1pyMRbzWkqQ7UD7Hyfbc_lU-OXuxFOz1XUtMchcW01po/edit?ts=597f5afb#slide=id.p

Some ideas we chatted through:
- using colour to orient each space/floor
- stickers on the floor to help navigate through space
- possible printers and budget
- white board / hackable sign for the info booth
- large banners from big spaces when they look up it helps guide them (ground and 4th floor)
- reference for in-person preparation time (for more ambitious installations like degree show)

**Comment by sabrinang** [comment]
Today I chatted with Katharine from DigitalMe about wayfinidng + badging throughout MozFest space. The concept was to reveal opportunities to earn badges and display additional wayfinding information via an AR app they are making. There would be approximately 25 badges _(6 spaces x 4 badge types (lab/gallery/shed/meta) + 1 volunteer = 25)_. When participants earn badges there may be rewards and prizes. The digital platform they view these badges are on our directory on [Open Badge Academy](https://www.openbadgeacademy.com/mozilladirectory).

How it affects design:
- the AR code itself could be the MozFest logo (with premium account?) so this wouldn't be intrusive with existing design plans (we would need to know code specs)
- information booths and/or floor maps can include AR code _(to show additional information via subtitles in different languages to showing .gifs or videos)_
- AR code stickers to customize other printed assets
- Hackable session signs and/or lanyard card can leave space for these stickers if they are not embedded
- make a How-to poster so participants understand how to reveal this additional information (perhaps upon entry or near participation guidelines)

Design assets to share with DigitalMe:
- Style Guide
    - 6 space icons
    - 3 session type icons 

Katharine will help provide:
- badge and AR code guidelines
- content for How-to poster

**Comment by EsmeSimcox** [comment]
I really like this idea of badges for each area, that shows information in addition to the information booth. When looking around Ravensbourne yesterday we came across these display boards, that the graphics department used for the degree show, which would be perfect for the information boards instead of the purple boards. What do you think?
![screen shot 2017-08-02 at 11 35 26](https://user-images.githubusercontent.com/30292263/28869971-84fea924-7776-11e7-8ff9-fde3100a7063.png)

**Comment by sabrinang** [comment]
@EsmeSimcox thanks for sharing more options for the info booth! Are there at least 6 peg boards? Will let you know if these or the purple boards fit the style more as the visual direction develops.

**Comment by EsmeSimcox** [comment]
@sabrinang I believe so yes, but I will ask Ravensbourne to check that too.

**Comment by EsmeSimcox** [comment]
@sabrinang I have had confirmation back in regards to the peg boards, and we are sadly unable to use them.

**Comment by sabrinang** [comment]
**Note to self:** Contact Katharine (integrate wayfinding badge/AR code guidelines or how-to on space info booth totems)
