### ISSUE TITLE
Social Media: Update Profile + Cover Photo

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#19]
Mozfest is on social media properties and their profile photos and header cover photos can use a refresh.

Examples of what we can update: 

Twitter
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2492510/28888096-344c0aaa-7774-11e7-85fe-36bebc4d73f5.png">

Flickr?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2492510/28888144-63555536-7774-11e7-9e42-b4696240a54e.png">

Medium?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2492510/28888128-539df04e-7774-11e7-91d6-960592f50b41.png">

I don't think we have an official facebook event or page so we don't have to worry about it unless there is. Please leave feedback below if there are other platforms to consider.

**Comment by tlasadea** [comment]
Hey @marcwalsh which designer is doing this? @beccaklam wasn't briefed on this so not sure if she has capacity this week. cc @HPaulJohnson

**Comment by sabrinang** [comment]
@tlasadea I filed this a while ago - I can cover this next week

**Comment by tlasadea** [comment]
Ahh thank you @sabrinang!!!

**Comment by sabrinang** [comment]
@tlasadea Here are some header backgrounds and profile image: https://drive.google.com/open?id=0B4Q8pzCpDS_eM3g5aGdwVm5oRXM
