### ISSUE TITLE
Schedule App Branding (Guidebook)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#20]
### Description:
This year we are using Guidebook's branded app and there are a few design elements to prepare for it: 
- [x] App Icon
- [x] Promotional Image
- [x] Splash Screen
- [x] Homepage Logo
- [x] Cover Image
- [x] App Screenshots
- [x] Colour Scheme
- [x] Menu Icons

Guidebook has [support](https://support.guidebook.com/hc/en-us/articles/115002968827) on how we can customize as we build the app.

Note: We should pay attention to colours and icon size to ensure that they are legible and accessible. 
__________________________
#### Timeline
Start work on App Design and Store Listing    9/20/2017
Finalise App Design    9/22/2017
Publish Guide    9/22/2017
Send app for guidebook review (Guidebook Duty 48hrs).    9/25/2017
App Submission    9/27/2017
App Launch    10/7/2017
Event date    10/27/2017

cc/ @mmmavis

**Comment by marcwalsh** [comment]
Hi @sabrinang - I've uploaded the branding specs that Guidebook sent over to us this morning - it includes a bit more info on dims etc.

Would you like me to create separate issues for each piece?

[Guide Book Branding Specs](https://github.com/MozillaFoundation/mozfest-design-2017/files/1313847/branding-specs.pdf)

**Comment by sabrinang** [comment]
Redpen here for feedback: https://redpen.io/p/cka334ade1ad2506dc
I'm not too sure where the promotional image appears in context, I might iterate on it with a lighter gradient.
![overview](https://user-images.githubusercontent.com/2492510/30623275-6f1cd020-9d6b-11e7-9d0f-d94d085abae7.jpg)

**Comment by sabrinang** [comment]
I'll be updated the gdrive folder here: https://drive.google.com/open?id=0B4Q8pzCpDS_edGwtYnJzNzZaRHM

**Comment by marcwalsh** [comment]
Hey @sabrinang - I placed these into Guidebook as placeholders. See the screenshots below about the usage :) 

![screen shot 2017-09-20 at 14 19 10](https://user-images.githubusercontent.com/30226684/30646011-70750dc6-9e0f-11e7-8309-990526cabae6.png)

For the splash screen it requires the image as one. The canvas should be the background size and the logo elements need to be contained within those dimensions due to cropping on different devices. This is the preview they gave below based on the max crop factor:

![screen shot 2017-09-20 at 14 18 51](https://user-images.githubusercontent.com/30226684/30645970-52488724-9e0f-11e7-8516-dc1790ec1756.png)

**Comment by marcwalsh** [comment]
Here are the previews of the colour scheme:

![preview1](https://user-images.githubusercontent.com/30226684/30646302-73b3daac-9e10-11e7-88cc-61b8b4a9621e.png)

![preview2](https://user-images.githubusercontent.com/30226684/30646304-770fa0b4-9e10-11e7-8367-a0e3db41298d.png)

**Comment by sabrinang** [comment]
Icons are updated and cover image (also updated in the [gdrive](https://drive.google.com/open?id=0B4Q8pzCpDS_edGwtYnJzNzZaRHM))
<img width="794" alt="screen shot 2017-09-21 at 5 44 03 pm" src="https://user-images.githubusercontent.com/2492510/30724691-82193a1c-9ef4-11e7-8d15-a7452cf7eb51.png">

Adjusted promotional image (no text and lighter gradient art)
![overview](https://user-images.githubusercontent.com/2492510/30724700-94d423d8-9ef4-11e7-9b1d-f9b8053c9b41.jpg)

**Comment by sabrinang** [comment]
Schedule app branding is live - closing ticket! 
<img width="971" alt="image" src="https://user-images.githubusercontent.com/2492510/31459112-0997ba4a-ae77-11e7-9558-b63986865088.png">
