### ISSUE TITLE
Swag: Name Card ID

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#21]
### Description:
Refresh the design of the name card ID that participants will wear on their lanyard.

### Content from 2016

**Front:**
- Mozilla Festival 2017 wordmark and or Tagline
- Empty area (for name, social media handles, stickers etc.)

**Back:**
* WiFi: [network name and password]
* Help: Tweet #MozHelp or visit the Info Desk on floors X, X and X.
* Schedule: [schedule shortlink]
* Lunch: From 12:30 - 14:00 on floors X, X and X.
* Coffee: Always hot on Floors X, X and X.
* Connect: #MozFest on Twitter, Instagram, Flickr and [Network Pulse shortlink]
* Safety: Approach the Info Desk on Level 5, email festival@mozilla.org or call [number] (all reports will be held in the strictest confidence)

### Print Deadline:
October 12th

### Blockers: 
- 2017 style guide

### Reference from Last Year: 
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/148
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLZ29Fb3dNcVE3alU

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/2492510/29680259-e30ce91a-88b8-11e7-9bc5-4a151d9b7d6e.png">

__________________________
#### Deadline
GanttStart: 2017-10-04
GanttDue: 2017-10-12

**Comment by edrushka** [comment]
For the MozFest weekend, we need two versions of the name card:
1) full festival weekend card (content in comment above)
2) science fair only card (doesn't need "lunch" content, if we decide to include that in the full festival card)

We need something that stands out in the design (perhaps a different colour background?) to indicate the different ticket types.

**Comment by sabrinang** [comment]
some WIP on some icons I created to go with the categories for clearer information hierarchy and experimenting with colour/textures
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/2492510/29727437-b571da80-8988-11e7-81cb-07fe154695ff.png">

**Comment by edrushka** [comment]
Ohhhh nice! I love textures on the front! 🎨 

@Saallen @marcwalsh can we go with the lanyard attached in two spots again this year? I know it took volunteers a lot longer to attach the lanyards to the cards. IMO, it's worth the effort so the card doesn't flip around and hide people's names.

**Comment by marcwalsh** [comment]
+1 for attaching the lanyard in two spots! It also means they are less likely to break...

**Comment by Saallen** [comment]
Looking good @sabrinang 
I would advise having the welcome desk as the focus for raising any issues- more staff and volunteers here- Raves run the 5th floor desk.
@marc to confirm wifi info

**Comment by Saallen** [comment]
Looking good @sabrinang 
I would advise having the welcome desk as the focus for raising any issues- more staff and volunteers here- Raves run the 5th floor desk.
@marc to confirm wifi info

**Comment by marcwalsh** [comment]
WiFi Confirmed! 📶📡 - @sabrinang 

Network Name: Rave
Password: mozfest17

**Comment by sabrinang** [comment]
Iterations on redpen here: https://redpen.io/p/fwd6e45324b8a54452
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/2492510/30347984-abe72ee6-97c2-11e7-944c-69ebfd19e997.png">

@xmatthewx After chatting about MozFest house, I made an alternative version with a different colour and visual marker on the lower right (with the word house and a simple icon logo). Does it look enough as a spin-off?

@edrushka What content goes on the back of the MozFest house name card ?

**Comment by edrushka** [comment]
House card information being tracked in https://github.com/mozilla/mozillafestival.org/issues/739

**Comment by xmatthewx** [comment]
@sabrinang 
 - I love the colors, the empty hex works well. I also like the "cut corner" black triangle as a modifier that could be applied to different things. 
 - I think the MozFest logo needs the gear icon in its lockup on the house materials. It feels very different without it and, at a glance, signals Mozilla not MozFest. 
 - While I like the house icon, I think it creates too much of a new brand rather than something that's inseparable from MozFest. It dilutes the brand and our chance to build awareness. Sorry if my input yesterday was ambiguous or confusing. Does that make sense? Some people coming to a house event will be more familiar with the specific event than with Mozilla or MozFest. We need to build connections with those brands, not introduce something new. For someone already familiar with MozFest, your icon is a nice extension. For everyone else, it reduces their chance to become familiar with MozFest. Given limitations with the venue, these people won't be surrounded with things to teach them about MozFest. What do you think?

**Comment by lucieclick** [comment]
Hi MozFest House WIFI info is - 
Network: RWNET
Password: 1986759

**Comment by sabrinang** [comment]
Content updated, please review content such as schedule link on redpen: https://redpen.io/p/fwd6e45324b8a54452

Files will be updated in gdrive: https://drive.google.com/open?id=0B4Q8pzCpDS_ecy1WdmQwUC1vRFk

**Comment by sabrinang** [comment]
Note: We need to include a different colour card to signal the difference of Friday only attendees

**Comment by sabrinang** [comment]
@edrushka Please review content/design of all 3 name cards - Redpen is updated with different colour Friday Only name card ID: https://redpen.io/p/fwd6e45324b8a54452

**Comment by edrushka** [comment]
✅  MozFest front: R+ content and design
 🔺 MozFest back: made some notes on content
✅ House front: R+ content and design
✅ House back: R+ content and design
✅Friday front: R+ content and design
🔺Friday back: need to replace/remove coffee

**Comment by sabrinang** [comment]
Thanks for the review @edrushka

Redpen is updated with changes: https://redpen.io/p/fwd6e45324b8a54452
.pdfs exported here with bleeds: https://drive.google.com/open?id=0B4Q8pzCpDS_eaGVLSVBua1o5a1k

Is this ready for print now?

**Comment by edrushka** [comment]
I'm ready to send this to print but @marcwalsh can you please do one final check of the back of lanyard content (wifi info, lunch and coffee locations and emergency phone number) before you send to printers.

cc @Saallen

**Comment by edrushka** [comment]
Sarah signed off in Slack. Send these to print! :shipit:

**Comment by sabrinang** [comment]
3 print .pdfs files here: https://drive.google.com/open?id=0B4Q8pzCpDS_eaGVLSVBua1o5a1k

@marcwalsh Ready for print!

**Comment by marcwalsh** [comment]
Sent to print!

**Comment by sabrinang** [comment]
## Post MozFest House Documentation

Name cards with information on the back available to be customized with sharpies at registration. Looks like Fuzzy brought his own lanyard! We supplied purple and yellow to go with them. 

![mozfest-house-45](https://user-images.githubusercontent.com/2492510/32525267-749405da-c3d8-11e7-9cfe-3b0e0bb1b0a6.jpg)
![mozfest-house-1](https://user-images.githubusercontent.com/2492510/32525454-64bf862e-c3d9-11e7-9450-3669f69ce7e6.jpg)

## Post MozFest Documentation
At registration you can pick up your lanyard with either a purple or yellow lanyard:
![mozilla-festival-2017-195](https://user-images.githubusercontent.com/2492510/32971892-45cfa7c6-cba4-11e7-9588-cb558197fb6d.jpg)

The Friday only lanyard was green. The back of the name tag had useful information on hand and you could customize it with language or pronouns stickers:
![20171027-mozfest-swag-4](https://user-images.githubusercontent.com/2492510/32971970-ab15a004-cba4-11e7-82cb-6e768d981224.jpg)

There was space for people to get creative with just sharpies:
![mozilla-festival-2017-263](https://user-images.githubusercontent.com/2492510/32971913-6a23ad98-cba4-11e7-9275-6f420e6d2000.jpg)

There was a braille label maker that you can customize your name tag too from the accessibility table: 
![mozilla-festival-2017-264](https://user-images.githubusercontent.com/2492510/32971916-6fd1191a-cba4-11e7-97d1-f4ef3d498eda.jpg)

You can collect stickers from the spaces:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/2492510/32972053-1aa7f3a4-cba5-11e7-8c56-e6f262cda21d.png">

The open leaders made their own hexagon stickers available at the customization table too - I was impressed how on brand it was!
<img width="679" alt="image" src="https://user-images.githubusercontent.com/2492510/32972081-44884fc0-cba5-11e7-9754-631db11ad3f1.png">
