### ISSUE TITLE
Photo treatment for media page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/mozfest-design-2017#22]
Hi @sabrinang - can you please give this photo a colour treatment so we can use it for the media page? Thanks!

https://user-images.githubusercontent.com/2492510/29726897-88553620-8986-11e7-9fe2-18858c266104.png

**Comment by mmmavis** [comment]
tagging myself here @mmmavis

**Comment by sabrinang** [comment]
@mmmavis Banner for the media page:
![media-banner 2x](https://user-images.githubusercontent.com/2492510/30135814-47c834c4-9311-11e7-95aa-d0ba2b8fa46c.jpg)

**Comment by mmmavis** [comment]
Hey @sabrinang could you export the image without the slanted lines? Like every other hero banners on the site, the slanted lines will be added via CSS. /////

**Comment by sabrinang** [comment]
@mmmavis Yes! Sorry I forgot - here is the original and retina versions if you need:
![media-banner](https://user-images.githubusercontent.com/2492510/30183105-05e7c20a-93ce-11e7-8a6a-fe8fa4c9c1a9.jpg)
![media-banner 2x](https://user-images.githubusercontent.com/2492510/30183106-05e9ad9a-93ce-11e7-91c5-2ca6b6ce947f.jpg)

**Comment by mmmavis** [comment]
Awesome. Thanks!
