### ISSUE TITLE
Swag: Mozilla Festival Stickers

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#23]
### Description:
We want to create some event stickers for MozFest and for the pre-week events too. 

**Main small sticker ideas:**
- MozFest Logo (do we want to include "2017"?)
- MozFest Tagline _(Web for All)_

**Other ideas include:**
- Generic Mozilla (stickers to reuse at other events)
- 6 Spaces/IH Areas 

Sticker supplier: https://www.stickermule.com 

### Previous Applications
Last year we had three types of stickers: 2 tagline and 1 logo lockup
![dsc06852-small](https://cloud.githubusercontent.com/assets/2492510/20154648/35372c1a-a67d-11e6-8a44-88380e5ed875.jpg)

### Related Issue
Sticker concepts: #18 

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0BzVQTTEXQZdXX2VONnRtdnJrcGs
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/80

__________________________
#### Deadline
GanttStart: 2017-08-28
GanttDue: 2017-09-01

**Comment by sabrinang** [comment]
I made some stickers that would be great on [clear vinyl](https://www.stickermule.com/ca/products/clear-stickers):
- MozFest Lockup that includes 2017
- MozFest Tagline (2 Versions)
- Generic Mozilla (stickers to reuse at other events)

<img width="927" alt="image" src="https://user-images.githubusercontent.com/2492510/30454736-39625062-9952-11e7-803e-e0ba8267af91.png">

I also made
- 6 space stickers
<img width="964" alt="image" src="https://user-images.githubusercontent.com/2492510/30454709-1bdfd366-9952-11e7-9c5b-9dca86e3bba2.png">

Redpen here for feedback: https://redpen.io/p/ka33b44c1567fe7db5

**Comment by sabrinang** [comment]
Space stickers redpen updated: https://redpen.io/dxa2ba7565ab94ab6a
Gdrive folder: https://drive.google.com/open?id=0B4Q8pzCpDS_eanBoNDVaOXc4OVk

Mozfest / web for all lockup stickers redpen updated: https://redpen.io/rpc05ea3aca6dbbb22
Gdrive folder: https://drive.google.com/open?id=0B4Q8pzCpDS_eZGZTakRTVmF6X2c

@edrushka Content/design review for these sticker sets?

**Comment by edrushka** [comment]
✅ Space Stickers R+
✅Lockup
🔺 Web for all - the contrast seems way lower on [this redpen](https://redpen.io/rpc05ea3aca6dbbb22) than on the [image in the previous comment](https://user-images.githubusercontent.com/2492510/30454736-39625062-9952-11e7-803e-e0ba8267af91.png). Is that intentional or an export gremlin?

**Comment by sabrinang** [comment]
@edrushka I changed the gradient all together (since it's on clear vinyl I was thinking the light full sticker can be stuck on dark surfaces and the other on light and made it less orangey in case it printed on the brown side)

**Comment by sabrinang** [comment]
It is also the same gradient I used for the large floor web for all sticker

**Comment by edrushka** [comment]
Ok. Just wanted to confirm it was intentional. 👍 Thanks for clarifying.

✅ Web for all stickers  R+

**Comment by sabrinang** [comment]
Thanks for the review! I evened out the gradient slightly: https://redpen.io/rpc05ea3aca6dbbb22

MozFest Lockup + Web for all Tagline sticker files (.ai/.pdf) here: https://drive.google.com/open?id=0B4Q8pzCpDS_eZGZTakRTVmF6X2c

Space sticker files (.ai/.pdf) here: https://drive.google.com/open?id=0B4Q8pzCpDS_eanBoNDVaOXc4OVk

@marcwalsh These are ready for print!

**Comment by marcwalsh** [comment]
Sent to print!
