### ISSUE TITLE
Swag & Name Card: Language + Pronoun Customization Stickers

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#24]
### Description:
These language stickers help declare what languages the attendee can converse in and these are displayed on their name card.

**The sticker can contain:**
- "I speak" in English
- Localized language name
- ISO 639-1 code (two-letter classification code)

**Print requirements:** 
matte (non-glossy) finish so pen/markers can write on them easily and these can be printed on sheets

### Previous Applications
Attendees have used these stickers to customize there name card with core languages or invited to write their own on blank "I speak" stickers at the "customize your name card" station at near registration
![mozfest-documentation-language-stickers](https://cloud.githubusercontent.com/assets/2492510/20158777/636bc7d0-a691-11e6-8478-fe469dd3630b.png)

### Blockers
Determine what 6-7 languages are our core languages this year https://github.com/mozilla/mozillafestival.org/issues/690

### Related Issue
Swag: Name Card ID: https://github.com/MozillaFoundation/mozfest-design-2017/issues/21

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLUW9FTWxNTGJGWnc
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/149

__________________________
#### Deadline
GanttStart: 2017-09-04
GanttDue: 2017-09-08

**Comment by sabrinang** [comment]
Looking at last year’s design, I would prefer to not have english (I speak) on each sticker and included a visual icon instead to keep each sticker localized. 
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/2492510/30333692-63338e04-9792-11e7-980a-b119c9a39c22.png">
I did consider some flag inspired gradients but it may get too visually busy and flag inspired gradients [may not reflect the language well](http://www.flagsarenotlanguages.com). We can keep these stickers a lighter tint of colour with some halftone dot textures. 

I’m using sticker mules' [sticker sheets 11” x 8.5” template](https://www.stickermule.com/template/sticker-sheets) (approx 32 stickers per sheet).
<img width="696" alt="image" src="https://user-images.githubusercontent.com/2492510/30333745-8fab9346-9792-11e7-82e3-fa8ce953a462.png">

The size of each sticker is around 1.5" x 1.7" and testing out what colour would stand out with the card.
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/2492510/30336912-852edae6-979b-11e7-9b9d-a3f9147023c6.png">

Waiting on two localized language names on ticket: https://github.com/mozilla/mozillafestival.org/issues/735#issuecomment-328215043
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/2492510/30337140-3bc8f304-979c-11e7-8456-18b1362e2292.png">

**Comment by sabrinang** [comment]
redpen here: https://redpen.io/p/fwd6e45324b8a54452

**Comment by edrushka** [comment]
Please make a "my pronouns" sticker using this same template.
Colours should work for both MozFest and MozFest House namecards.
No little man. Text is: My pronouns:

**Comment by TheoChevalier** [comment]
I wonder if having the “speaking icon” after the language name could be confusing. Seeing “Français” alone, I have more the impression that it means I’m French, and not that I speak French.

One could understand it as the spoken language info is only on the second line and the first line is about nationality.

**Comment by edrushka** [comment]
Please add the "I speak" back to the top of these stickers. thank you.

**Comment by sabrinang** [comment]
@edrushka When I am adding "I speak" is it in english or is it using its own language?
<img width="749" alt="image" src="https://user-images.githubusercontent.com/2492510/31256506-d035abb0-a9e7-11e7-9ecc-84cc36df668b.png">

**Comment by edrushka** [comment]
Oh, if we have it localized, let's go with that!

**Comment by sabrinang** [comment]
Customization stickers updated on redpen: https://redpen.io/fw0472330f261739a6
<img width="821" alt="image" src="https://user-images.githubusercontent.com/2492510/31299454-5a2646b6-aaa3-11e7-86f5-6d0c0f313841.png">
@edrushka  Can you review content/design?

**Comment by TheoChevalier** [comment]
@sabrinang Small detail, but could you update the language name with the same capitalization as in the translation? E.g français vs. Français

I think it will help even more to make the distinction between citizenship and language. Example in French:

Le français = the French language
Le Français = the French citizen

Previously it was technically the first and unique word of the sentence, so using a capital letter was okay, but now it’s in the middle of a sentence.

Rules are different for each language, so let’s trust what’s in the dashboard: we should keep the capital letter for German and Portuguese, remove it for French, Italian, Spanish.

Let me know if me comment is making things confusing :)

**Comment by edrushka** [comment]
R+ on design 
I've asked viki  and Mavis on Slack to review the Hindi and Chinese stickers.

**Comment by sabrinang** [comment]
@TheoChevalier Thank you for review! I updated the redpen so the capitalization follows the dashboard: https://redpen.io/fw0472330f261739a6

@edrushka Can this be sent to print?

**Comment by edrushka** [comment]
R+

**Comment by sabrinang** [comment]
Name card customization sticker files (.ai/.pdf) are here: https://drive.google.com/open?id=0B4Q8pzCpDS_eOWIwNnBhSHVrWFk

@marcwalsh These are ready for print!

**Comment by marcwalsh** [comment]
Sent to print!
