### ISSUE TITLE
Stages: Main and Secondary Printed Backdrops

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#25]
### Description:
Previously we had two stages:
- the Main Stage on Level 4 
- the Secondary _(Dialogue and Debates Stage)_ in the Walker Space on Level 0

These had a printed backdrop, two screens, one comfort monitor (no have a podium or projector).

#### Things to Consider
- Both stages should have related designs to each other
- Talks will be streamed and recorded from Secondary stage
- This is a good opportunity to think about how branding shows up in video frames and the design should not be too busy (avoid close repeating line patterns etc.).
- Stages have artificial lights directed on them (Walker room will be artificially lit because there are no windows or natural light)
- MozFest Wordmark and Tagline (may incorporate some l10n taglines) should be included

#### Last year's dimensions
**Format:** High Res 100% (Actual Size) image size either PDF or EPS for each image.
**Size:** 4800mm x 2400mm
**Bleed:** 100mm bleed

<img width="891" alt="image" src="https://user-images.githubusercontent.com/2492510/29784839-5d9a366e-8bda-11e7-9725-7de4827d77ab.png">

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eOEZHUURrSUVKWG8
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/103

### Previous Application
The Main Stage on level 4 had lights along the bottom with a table set up to the right.
![30637012765_bb7326f890_o](https://user-images.githubusercontent.com/2492510/29784737-03ad7efe-8bda-11e7-895c-a141857fd7ab.jpg)

The Dialogue and Debates Stage in the Walker Space on level 0 had a lighter background treatment which contrasted the dark space and the yellow strip below peaked through under the stage lights.
![mozfest-documentation-swag-18](https://user-images.githubusercontent.com/2492510/29784645-ab05dc38-8bd9-11e7-8533-3de4f3674558.jpg)
________________________
#### Deadline
GanttStart: 2017-09-11
GanttDue: 2017-09-15

**Comment by sabrinang** [comment]
@edrushka Can I get some feedback for content/design for stage designs on redpen?  https://redpen.io/p/zs39406b73bc7dd0f6

**Comment by edrushka** [comment]
Marc and I reviewed and left feedback in the redpen. cc-ing @KevZawacki for review as well.

**Comment by KevZawacki** [comment]
@edrushka @sabrinang This is perfect!

**Comment by marcwalsh** [comment]
@sabrinang - Could I get ready for print today, please? The printers need it by tomorrow morning UK time. 

The 100mm bleed is perfect!

**Comment by sabrinang** [comment]
I made the gradient transitions softer and used dark logo for floor 0 stage: https://redpen.io/p/zs39406b73bc7dd0f6
<img width="933" alt="screen shot 2017-10-17 at 7 14 59 pm" src="https://user-images.githubusercontent.com/2492510/31704000-2de496e4-b394-11e7-9ff1-d46dca9a6dbc.png">

@edrushka Let me know if this works if it is good to go @marcwalsh print files are below:

Floor 0 - Print Files (.pdf / .eps): https://drive.google.com/open?id=0B4Q8pzCpDS_eLXFOSnQ2bEZwWHM
Floor 4 - Print Files (.pdf/ .eps): https://drive.google.com/open?id=0B4Q8pzCpDS_eYUY4SmxuSmxFY0E

**Comment by edrushka** [comment]
These have been sent to printer. Apologies for my unclear comment in redpen - I was thinking of the lighter version for the D&Ds and the darker version for the 4th Floor mainstage (both are same dimensions so we can swap). @KevZawacki what is your preference for the D&Ds?

**Comment by KevZawacki** [comment]
@edrushka No preference from me — whatever's easiest

**Comment by edrushka** [comment]
I think the darker will look better on the mainstage because it's so naturally bright there. Worried that in the dark D&D room, the darker will be contrast-y on camera. I'm not an expert though, and would suggest we consult with Mac from AV.

**Comment by marcwalsh** [comment]
Sent to printers - I'll let Whitelight know about changing around the stages.

**Comment by edrushka** [comment]
## Post MozFest Documentation

Colour, quality and materials were good but scale of backdrops and placement were off this year. Screens were placed on the ground both on the 4th floor and in the Walker Space, instead of the stage, so lockups were at an awkward height, especially for taller speakers. Also, top edge of backdrop was visible in more photos this year.


AirMo screenshot showing awkward lockup height:
<img width="937" alt="screenshot 2017-11-24 12 48 01" src="https://user-images.githubusercontent.com/4515662/33223688-c051c840-d116-11e7-859e-e09fe56e260c.png">

**Comment by edrushka** [comment]
Additional notes re: backdrops. 4th Floor and Walker Space backdrops got swapped. This looked fine, but the slide templates for each space didn't match the backdrops. Ensure stage crew has photo references for each stage/slide setup.

**Comment by sabrinang** [comment]
Scale of this year was quite a bit smaller than the year before and it was set up from the ground (not propped up).
![mozilla-festival-2017-128](https://user-images.githubusercontent.com/2492510/33223779-d987474e-d117-11e7-9518-85b3b8ceccdd.jpg)=
![mozilla-festival-2017-130](https://user-images.githubusercontent.com/2492510/33223750-8e6bcb18-d117-11e7-9786-d3fa035f23f4.jpg)
![30337169970_003f6a5c90_o](https://user-images.githubusercontent.com/2492510/33223754-9af18f12-d117-11e7-8271-e68fd97e6c2b.jpg)
