### ISSUE TITLE
Wayfinidng: Registration Table Signage

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#26]
### Description:
When attendees enter the venue, there are a few registration tables set up and signage to help identify the various stations to guide them through the process and signs help make the tables look more official so people know where to go.

**This collection of signs include:**

- [x] Welcome sign (with l10n incorporated) https://github.com/mozilla/mozillafestival.org/issues/720
- [x] Sign-in & Register Here
          - check name off list
          - receive name card id
          - participation guidelines
- [x] Customize Your Name ID
          - marker station to write name
          - language sticker area
          - icebreaker sticker area
- [x] Collect Your Swag
          - festival guide, water bottle, stickers etc.
- [x] Youth & Press & Accessibility
- [x] MozFest Wordmark banner in the front of the table

**Format:**
Last year the Youth & Press sign was a different size from the rest and we can unify the formats this year. I think A4 was a bit small to read from a far so I recommend using A3 (297 x 420 mm) as an option (Youth & Press was A2).

Also, I would consider the Collect your Swag station to be at the end (since there was various waterbottles/guides left at the customization station and people won't have to fumble with stuff as they make their name cards look fancy.)

### Previous Applications
We used masking tape to adhere signs on edge of the folding tables. 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/2492510/29791595-5d3d0abc-8bf2-11e7-81c6-8522cc41e5fd.png">

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/file/d/0B4Q8pzCpDS_eUmRKcHIyeVVHZHc/view
Youth & Press: https://drive.google.com/open?id=0B2irLVDJivhLdU54eEJScmpVZ3c
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/201

__________________________
#### Deadline
GanttStart: 2017-10-02
GanttDue: 2017-10-06

**Comment by edrushka** [comment]
Since we're tight on QA time, recommendations for the localized welcome sign:
- avoid languages (except zh-TW and hi-IN because you know the fonts) that don't use Latin alphabet
- if you have a font for Arabic, that one is ok because Theo can quickly get it reviewed
- avoid Slavic languages as there can be font issues with those

**Comment by sabrinang** [comment]
I used the language from https://transvision.mozfr.org/string/?entity=mobile/android/base/android_strings.dtd:firstrun_panel_title_welcome&repo=central to use welcome in other languages in the background similar to last year:
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/2492510/31255957-82105a14-a9e4-11e7-95f4-7637634d466a.png">

@edrushka I removed languages that didn't have fonts on my computer and I started this process before I saw the comment above so I am unsure which ones are Slavic and I will have to go back in and remove non-latin alphabet ones if that is still the case. Last years was A4 this one is is designed as A2 but can export the desired size.

The redpen is here: https://redpen.io/p/em51633306aa00fca3

**Comment by edrushka** [comment]
Ah ok! I wasn't sure if you'd started on this. I definitely don't want you to redo work and we didn't get any complaints about the 2016 poster so disregard my previous comments. 

@TheoChevalier do we need to QA this if Sabrina used the firefox strings and no one pointed out errors on last year's poster?

**Comment by sabrinang** [comment]
The 2016 poster was really small but last year I just used a random source since it was a last minute addition last year though but I doubt anyone looked closely at it but this year I used the transvision source that Theo provided this year

**Comment by sabrinang** [comment]
@edrushka Can you give me some content/design feedback on [redpen](https://redpen.io/p/bp2d4be582ee564376) for the four register table signs: 
- Sign-in & Register Here
- Customize Your Name ID
- Collect Your Swag
- Youth & Press & Accessibility

Also any thoughts on sizing? I was thinking they can all be A2 like the Youth & Press poster last year so it can go along the front of the table and be seen from far away (minimum they should be A3).

**Comment by edrushka** [comment]
Lovely! Left feedback. Looks good but some thoughts on the ampersand in Youth, Press and A11Y, and a word replacement. I'd go with same size as last year (A2).

**Comment by marcwalsh** [comment]
Since it's single run let's go for cardboard on A2:

[A2-Pixart-Template.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1396607/A2-Pixart-Template.pdf)

**Comment by sabrinang** [comment]
@marcwalsh Do you think we should go with a shorter height than A2 since the cardboard will be sticking up over the table... last year it was a flexible poster so it sorta folded over (kinda sloppy though but not a big deal)
<img width="717" alt="image" src="https://user-images.githubusercontent.com/2492510/31791466-6e45be9a-b4cd-11e7-8180-97d76c374713.png">

**Comment by marcwalsh** [comment]
@sabrinang - A3 could work but it might be small... how about rotating so it's A2 landscape?

**Comment by marcwalsh** [comment]
@sabrinang - or I can get two of each in A3 so you don't need to redesign! :)

**Comment by sabrinang** [comment]
@edrushka Please review updated redpen that includes logo and welcome horizontal table banners: https://redpen.io/p/bp2d4be582ee564376

@marcwalsh Do we know the table heights yet (if not we can print on site to measure) and we could print the logo/welcome banners horizontal and large similar this size last year: 
<img width="268" alt="image" src="https://user-images.githubusercontent.com/2492510/31866954-d17d3ebe-b73b-11e7-95df-3284602aa741.png">

**Comment by edrushka** [comment]
R+ on registration and welcome banners. 

Would be great to have made-to-measure horizontal signs to look profesh.

**Comment by marcwalsh** [comment]
@sabrinang - sorry it took so long but the height is 72cm

**Comment by sabrinang** [comment]
@marcwalsh Print .pdf here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ebktZM3RsSklzNDg/view?usp=sharing

**Comment by taisdesouzalessa** [comment]
@marcwalsh - here they are to print.
[Mozilla-Festival-2017_Registration-Table-big1.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1422591/Mozilla-Festival-2017_Registration-Table-big1.pdf)
[Mozilla-Festival-2017_Registration-Table-big2.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1422592/Mozilla-Festival-2017_Registration-Table-big2.pdf)
[Mozilla-Festival-2017_Registration-Table-Posters_1-to-4.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1422593/Mozilla-Festival-2017_Registration-Table-Posters_1-to-4.pdf)


 I also sent those files to the Ravensbourne email.

cc: @sabrinang
