### ISSUE TITLE
Wayfinding: Info Booth for Spaces

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#28]
### Description:
At the entrance or stairway to each space or floor, we have a desk and pinboard stationed with space information for attendees. We can try [wooden peg boards](https://github.com/MozillaFoundation/mozfest-design-2017/issues/17#issuecomment-319635049) or purple fabric pinboards seen last year for this set-up.

**This collection of signs include:**

- [x] Space Poster (Name, Icon, Description) for all 6 Spaces
          - last year there was two and it may be redundant to have both
- [x] Information Symbol Poster
- [x] Participation Guidelines
- [x] Hackable Sessions Schedule Poster (Whiteboard, erasable material)
         - we did not have this last year but an idea to include

Space Descriptions: https://mozillafestival.org/spaces
Space Icons: _to be finalized_

### Previous Applications
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/2492510/29798082-a477f60e-8c0f-11e7-88fd-8280b6055119.png">

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B8D3YQVeWHo7X05ySDk5WlZaVnM
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/90

__________________________
#### Deadline
GanttStart: 2017-10-02
GanttDue: 2017-10-06

**Comment by sabrinang** [comment]
Let's consider using a standing totem as an option instead of the board set up: https://www.pixartprinting.co.uk/displays/point-of-sale-displays/totem-3-xl/

**Comment by tad124737337** [comment]
+1 to the totem suggestion. I found the boards to be "cluttered" and hard to read. I'm not sure how well we can present the more detailed information without the board, but if you have a proposal for that, I'd be very interested in providing feedback!

Perhaps we can use very simple advertising stands with printed information on top of the table.

**Comment by sabrinang** [comment]
I iterated on these info booth totems: https://redpen.io/p/bk58b0b4940ff0aba5
<img width="926" alt="image" src="https://user-images.githubusercontent.com/2492510/31684966-51b8ed1c-b336-11e7-92cb-8414c92b6162.png">
These include the info booth icon, short space description, map, participation guideline, hackable area to stick session information on and info on #mozhelp + sched

@edrushka Feedback on content/design?

**Comment by edrushka** [comment]
These are gorgeous!! 
- I commented in redpen that I prefer the white icon to the dark icon for Digital Inclusion (but I'm ok with either)
- On all floor maps, please change floor 4 to Main Stage/Emergent Sessions as per updates to the venue map
- @marcwalsh do we need to print fewer copies of the participation guidelines if they are integrated into the totem designs?

**Comment by sabrinang** [comment]
@edrushka Updated Main Stage/Emergent Sessions text on booths and using white icons except youth zone - please review redpen: https://redpen.io/p/bk58b0b4940ff0aba5

Print .pdfs here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eZUxJOHhvN0NWX2s?usp=sharing

**Comment by edrushka** [comment]
Note I haven't gone through copy w/a fine tooth comb.

**Comment by edrushka** [comment]
OK I've reviewed with my :eagle: :eye: Found one internet that needs to be capitalized but everything else is good. Marc, if you need to print these without fixing it's ok - not a critical typo.

**Comment by sabrinang** [comment]
@edrushka Good catch and Internet is now capitalized!

@marcwalsh Ready for print
print .pdfs here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eZUxJOHhvN0NWX2s?usp=sharing

**Comment by marcwalsh** [comment]
Sent for print!
