### ISSUE TITLE
Wayfinding: #MozHelp Desk Sign

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#29]
### Description:
Last year, the #MozHelp desk was On level 5. Design some signs to make this easy to find beyond the desk area.

**This collection of signs include:**
- [ ] #MozHelp desk sandwich board sign (A4 last year if we tap onto the side of a table perhaps A3)
- [ ] extra #MozHelp sign 
          - maybe export it with an arrow so it can be seen coming up from the stairwell
- [ ] #MozHelp banner 
          - that can go over the banister so it can be spotted from the floors below like our space banners

### Previous Applications
![30725957316_5531e2c9ca_k](https://cloud.githubusercontent.com/assets/2492510/20121210/09439840-a5c5-11e6-9f2a-77e0f3f7300e.jpg)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLc1lLQ0RsTW5TeW8
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/191

__________________________
#### Deadline
GanttStart: 2017-10-02
GanttDue: 2017-10-06

**Comment by tad124737337** [comment]
Our central helpdesk this year is going to likely be positioned on Floor 4's Ravensbourne desk. This is quite a big desk, and we want to make a large presence there. A large banner dropped down would be great.

**Comment by sabrinang** [comment]
@marcwalsh Do you have the dimensions/template of the sandwich board, poster or banner for this #mozhelp area?

@edrushka The design matches the deep cyan of the volunteer #mozhelp shirts, can you give me content/design feedback on redpen: https://redpen.io/p/mn47aa1bee24f27839

**Comment by edrushka** [comment]
Beautiful. R+

**Comment by sabrinang** [comment]
@marcwalsh Do you have the dimensions for this banner and templates for poster or sandwich board?

**Comment by sabrinang** [comment]
@edrushka  I made the banner/posters to be more red toned since volunteers will be wearing red now. Updated redpen: https://redpen.io/p/mn47aa1bee24f27839
<img width="668" alt="image" src="https://user-images.githubusercontent.com/2492510/31867058-7a8a58ce-b73d-11e7-9ce7-152c024e7f65.png">

@marcwalsh Let me know the dimensions of the curved table and if we need a specific size poster/sandwich board to go with it

**Comment by edrushka** [comment]
Love it! You are thinking of everything 😄

**Comment by taisdesouzalessa** [comment]
@marcwalsh could you please send the attached files to print here in Ravensbourne?

3 copies of this file: 
[signs-a4.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1421914/signs-a4.pdf)

1 of this file:
[signs-desk.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1421917/signs-desk.pdf)

cc: @sabrinang

**Comment by taisdesouzalessa** [comment]
@marcwalsh here are the new artworks, flat:
[sign-floor-flat.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1422384/sign-floor-flat.pdf)
[sign-table-flat.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1422385/sign-table-flat.pdf)
[signs-a4-flat.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1422386/signs-a4-flat.pdf)

They also told me to email: printshop@rave.ac.uk so I am doing that as well.
