### ISSUE TITLE
Swag Ideas

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#3]
Let's brainstorm what we want to give as swag. We can consider physical swag (_favouring more minimal or sustainable options_) and should consider digital swag (_reducing environmental impact and efficient way to add value for attendees_). Also, consider how much effort it may require for our volunteer to assemble or organize it together and reduce this dependency when possible.

Note: @edrushka mentioned to reach out to HR team, Jonathan, as he has done some thinking around swag across Foundation.

Brainstorm doc to get started in gdocs here: https://docs.google.com/document/d/1I6KwBy8IpUpt4Uvv03kI6F60GTHeP-Z9dxbJhvvDQo0/edit?usp=sharing

__________________________
#### Deadline
GanttStart: 2017-07-18
GanttDue: 2017-08-04

**Comment by sabrinang** [comment]
I reached out to Jonathan and he has done a lot of research already on physical swag: https://docs.google.com/a/mozilla.com/spreadsheets/d/1Xvnx2v3BuNgnL45MgEjz03scw5-IksNG1Js5CJi2yeg/edit?usp=sharing

I'm also curious to know what our MozFest audience enjoys receiving so we can prevent producing waste or things people don't want to take. I wonder if we can do some sort of poll/survey to also help decide on some ideas.

@marcwalsh-zz @JonathanLeonard we can keep track of the swag planning and ideas here.

**Comment by marcwalsh** [comment]
Thanks @sabrinang!

(Just FYI - I'm still using @marcwalsh, @marcwalsh-zz was from last year but I lost my 2FA recovery codes but managed to get my username back! 😅)

**Comment by sabrinang** [comment]
**2017 Swag**
- socks #51 
- travel-friendly rollable water bottle #53 
- notebook #44
- usb flash drive #79 
- branded stickers #23
- webcam blocker stickers (sticker mule)
