### ISSUE TITLE
Wayfinding: Floor Plan Maps

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#32]
### Description:
Update location of spaces and specific locations for this year and update the branding and colours. This content includes highlighting:

- Spaces
- Lunch areas
- Coffee
- D&D stage
- Main stage
- Prayer room
- Supplies room
- Creche
- Toilets
- Water
- #mozhelp
- info booth

**This collection of maps include:**
- [x] (1) Floor Overview Map
     - appears throughout the building specificallly near elevators, stairs, in foyer, at info booths
     - will this be in the festival guide this year?
- [x] (11) Current Floor Map
      - each floor has a different version
- [x] Backgrounds

**Format**
- A3 printed on cardboard

### Blocked by
- map content

### Previous Applications
<img width="423" alt="image" src="https://user-images.githubusercontent.com/2492510/29838395-f6edeb32-8caf-11e7-9b79-cf536677233a.png">
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/2492510/29838490-2a548e2c-8cb0-11e7-9f94-2203d4713385.png">

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLUU9JbDVUUjZoRXM
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/91

__________________________
#### Deadline
GanttStart: 2017-09-18
GanttDue: 2017-09-22

**Comment by sabrinang** [comment]
Revising maps designs with updated colours, new icons, update type (blanch and zilla slab), added lockup on lower left. Floors with spaces will use space colour which will be worked on when content is determined.
<img width="848" alt="test" src="https://user-images.githubusercontent.com/2492510/30832318-83adf6a2-a1ff-11e7-941e-c75540143f8c.png">

Blocked by map content TBD issue# ? and redpen: https://redpen.io/p/xf4cd10e88113df8d7

**Comment by cassiemc** [comment]
@edrushka @sabrinang Should I be using this design for the map insert in the festival guide? To add, the dependency here is that I would like to finalize the map insert alongside submitting the cover artwork – due Thursday p.m. – as I want to make sure the pocket and other dimensions are all working together precisely.

**Comment by sabrinang** [comment]
@cassiemc It would be the MozFest Site Map (the overview of all floors) design that will be in the insert for the festival guide - I have not yet revised each floor map yet (I just updated type/icons in the above example so I'd be ready to update when when content is complete). You can design the format the map insert for the festival guide like the tab that sticks out and the back of the map if it has a design and I can help with the updating the floor content.
@edrushka Do you know when the content for the maps will be complete and locked? https://redpen.io/p/xf4cd10e88113df8d7 is still missing the main spaces themselves

**Comment by edrushka** [comment]
@marcwalsh do you know when content for map will be complete? My understanding is that you and Esme own this piece. Please let me know ASAP if I'm mistaken.

**Comment by marcwalsh** [comment]
@edrushka @sabrinang  - Icon content is correct in the red pen. The blocker is the spaces and where they will be positioned. I think we're going over this in the next couple of days.

**Comment by sabrinang** [comment]
content ready on redpen: https://redpen.io/p/xf4cd10e88113df8d7

**Comment by sabrinang** [comment]
@marcwalsh Can you give me upload powers for the redpen: https://redpen.io/p/xf4cd10e88113df8d7 (didn't want to start a new one)

I made the floors coordinate with the space colours since it ties the wayfinding together and the old colours just didn't make sense with the new space colours. When I upload on these on the redpen, @edrushka can you indicate the specifics for floor 6 (only shared space)
<img width="955" alt="image" src="https://user-images.githubusercontent.com/2492510/31528491-67e154aa-af88-11e7-9c76-bea9350e4c63.png">

The other main thing to address is the desire for the stair-elevator combo thing, if we want stairs to be the main mode of transport should we leave it as is indicating stairs?

**Comment by sabrinang** [comment]
@edrushka Can you help review content and give me feedback on design? https://redpen.io/p/xf4cd10e88113df8d7

**Comment by edrushka** [comment]
I've reviewed and made one small comment about the 2 Artists Open Studios on the 6th floor (I don't think the design needs changes - having two icons side by side might look like an error).

I'm ok to sign off on design from my end but please be aware Marc and London-based team are more familiar w/content. They should review next week before sending to print.

**Comment by sabrinang** [comment]
I updated floor 6 with two artist open studios

**Comment by cassiemc** [comment]
@sabrinang Can you share the source files for the overview map please?

**Comment by sabrinang** [comment]
@cassiemc The .ai file here https://drive.google.com/open?id=0B4Q8pzCpDS_eZGxNblRWV1RKbTg contains the overview map (all in the same file just different artboards)

**Comment by sabrinang** [comment]
@Saallen @marcwalsh Internet Research Hub has been updated on maps: https://redpen.io/p/xf4cd10e88113df8d7

Can you give final review that content is good for print from what you see on the redpen?

**Comment by cassiemc** [comment]
@sabrinang I'm missing fonts apparently, can you outline all text in the overview map please?

**Comment by sabrinang** [comment]
@cassiemc I exported an outlined text version .ai: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eRnlzUGY0RFFxc00/view?usp=sharing

Sorry about that it must of had some alternative fonts previously (by revised last years file).

**Comment by sabrinang** [comment]
@marcwalsh Can you share the template I should use to export these? Unsure if these are printed on cardboard if the quality of printing isn't sharp

**Comment by marcwalsh** [comment]
@sabrinang - Let's go for A3 sized, same template and I'll print on foamex instead.

If we're having a background that would stay on cardboard if that's okay to reduce costs.

**Comment by sabrinang** [comment]
@edrushka floor 4 "Main Stage / Emergent Sessions" is updated on all maps: https://redpen.io/p/xf4cd10e88113df8d7  Is this content good to go?

@marcwalsh We are layering the maps like we did last year right? The maps themselves can be on foamex and backgrounds can be flat or poster whatever is cheaper (most of it is covered anyway)

I exported all these files on the A3-Pixart-Template.pdf I had before here: https://drive.google.com/open?id=0B4Q8pzCpDS_eVmluRV9vdWF3dWc

![maps overview](https://user-images.githubusercontent.com/2492510/31799292-09179716-b4ee-11e7-9f75-77d8ed203e6f.jpg)

**Comment by edrushka** [comment]
R+ looks good! 🎷

**Comment by marcwalsh** [comment]
(Note to self) Quantities Needed:

34x Generic Background - Cardboard
2x6 Space Specific Backgrounds - Cardboard
22x Generic Floor Maps - Cardboard
2x11 Floor Specific Maps - Cardboard

@sabrinang - I'm also going to get 2x A2 of the generic maps as well so there's something more prominent in the front entrance. I can rescale these myself from the PDFs. :)

**Comment by marcwalsh** [comment]
Sent to Print - ETA: Wed 25th

**Comment by sabrinang** [comment]
## Post MozFest Documentation
Youth Zone map - This is a specific example for space specific floor map:
![mozilla-festival-2017-267](https://user-images.githubusercontent.com/2492510/33190983-ac2c48f8-d068-11e7-86c0-39734881d905.jpg)
![20171027-mozfest-signage-30](https://user-images.githubusercontent.com/2492510/33191009-1b7b55f0-d069-11e7-83c8-09963f54167f.jpg)
Overview map:
![mozilla-festival-2017-268](https://user-images.githubusercontent.com/2492510/33190984-ac404ca4-d068-11e7-80b0-a4f6eb1f92c0.jpg)
![mozilla-festival-2017-269](https://user-images.githubusercontent.com/2492510/33190985-ac542b66-d068-11e7-9dd4-fae7196f560a.jpg)
![20171027-mozfest-signage-21](https://user-images.githubusercontent.com/2492510/33191008-1b68dd62-d069-11e7-8ef2-7c37e5484001.jpg)
Festival guide map version:
![20171027-mozfest-swag-21](https://user-images.githubusercontent.com/2492510/33191015-395bd374-d069-11e7-905f-91cd34a8e5f1.jpg)
Totem map version:
![mozilla-festival-2017-250](https://user-images.githubusercontent.com/2492510/33191090-311c4efe-d06a-11e7-9cb2-88596b6662c8.jpg)
![mozilla-festival-2017-238](https://user-images.githubusercontent.com/2492510/33191092-325276cc-d06a-11e7-8b22-e159d1abaf25.jpg)

**Comment by edrushka** [comment]
Printing feedback:
- foamcore/cardboard x2 (both layers) was too heavy for whitetack and fell off the wall. Recommend paper for background (this textured/coloured paper could have all sorts of uses!) and cardboard for the front. Could also have both layers as paper.
- 3D effect is really nice
