### ISSUE TITLE
Wayfinding: Space and Floor Number Banners

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#33]
### Description:
For the 6 spaces this year, design banners that hang from the balustrades seen from the foyer and atrium. The info booths also use a space banner. 

**Spaces include:**
- Youth Zone
- Privacy & Security
- Open Innovation
- Decentralization
- Digital Inclusion
- Web Literacy
 
**This collection of banners include:**
- [x] (6) Large Space Banners for hanging on banisters
- [x] Medium Floor Number Banners
- [x] (2 at entrance) Small Tagline Banners
- [x] (2 at entrance) Large Lockup Banners

**Format**
refer to last years issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/178

### Blocked by
space locations

### Previous Applications
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/2492510/29839973-2b7edf3c-8cb5-11e7-96d4-7c8981c4a101.png">
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/2492510/29839535-706f6cda-8cb3-11e7-84de-a007033a1343.png">
<img width="920" alt="image" src="https://user-images.githubusercontent.com/2492510/29839551-821533c0-8cb3-11e7-955a-74dcded80a18.png">

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/drive/folders/0B8D3YQVeWHo7VFo4TkNFUzZvTjg
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/178
https://github.com/MozillaFoundation/Mozfest2016_production/issues/102

__________________________
#### Deadline
GanttStart: 2017-09-18
GanttDue: 2017-09-22

**Comment by sabrinang** [comment]
@edrushka Can I get some content/design feedback on these wayfinding banners: https://redpen.io/p/kgdab16100c1d4c107

The main content question I have is - Do the floors without spaces need banners? (reference [here](https://redpen.io/av74b3a375e791819d?showing_comment=2736645))

**Comment by edrushka** [comment]
Sarah and I reviewed and I put feedback in the redpen. We like banners for the non-space floors.

**Comment by marcwalsh** [comment]
@sabrinang - Templates are available [here](https://www.pixartprinting.co.uk/wide-format/printing-banners-mesh/pvc-banner/) enter the size and press 'Template' and it will generate one for you. Not too sure of the sizing you want.

**Comment by sabrinang** [comment]
@edrushka Please review content https://redpen.io/av74b3a375e791819d

I made the floor banners brighter with bold number and did not use black. I simplified it with each floor having number + space (no tagline, looks too busy). The lockup + tagline combo can be two sets seen in the entrance area for this ticket https://github.com/MozillaFoundation/mozfest-design-2017/issues/30

Print .pdfs exported using custom Pixart templates
Large (100cm x 200cm)
Small (75cm x 150cm)
https://drive.google.com/open?id=0B4Q8pzCpDS_eV3dXRnNYM3U0dlk

**Comment by edrushka** [comment]
R+ from Sarah and I ❤️ ❤️ ❤️

**Comment by sabrinang** [comment]
@marcwalsh Ready for print!

Print .pdfs exported using custom Pixart templates
Large (100cm x 200cm)
Small (75cm x 150cm)
https://drive.google.com/open?id=0B4Q8pzCpDS_eV3dXRnNYM3U0dlk

Previously, we had 3 holes at the top of large banners and 2 holes for small banners so lets go with that again.

**Comment by marcwalsh** [comment]
Sent to Print! 🕺

ETA: Tuesday 24th

**Comment by sabrinang** [comment]
## Post MozFest Documentation
We printed floor numbers and space name/icon on large vinyl banners with two holes on top
![mozilla-festival-2017-4](https://user-images.githubusercontent.com/2492510/33220910-d453482a-d100-11e7-9212-eabfceef0710.jpg)
During installation, aligned the floor numbers vertically across floors which made it organized and easy to scan. The entrance had the wordmark and tagline banners hanging above registration.
![mozilla-festival-2017-39](https://user-images.githubusercontent.com/2492510/33220913-dad149cc-d100-11e7-8ac8-2b59ca47b791.jpg)
These were centered along the railing where possible and aligned vertically.
![mozilla-festival-2017-59](https://user-images.githubusercontent.com/2492510/33220986-4955c1b6-d101-11e7-935d-3182b435299c.jpg)
![mozilla-festival-2017-127](https://user-images.githubusercontent.com/2492510/33220927-f6eb65ca-d100-11e7-8beb-308293177fa5.jpg)
The shared floor also shared the number and it was a gradient of both colours. This coincidentally matched the side of the floor they were on as well
![mozilla-festival-2017-139](https://user-images.githubusercontent.com/2492510/33220938-00552a56-d101-11e7-8bff-726666b53dc2.jpg)
Floor banners were also made for non-space floors and we used a neutral blue. The spaces such as internet research hub and unbox had their own banners and did not know we were making floor banners for them. Unsure if unbox was used though.
![mozilla-festival-2017-208](https://user-images.githubusercontent.com/2492510/33220953-0e73f3e2-d101-11e7-93aa-6c3b26fa72c3.jpg)
![mozilla-festival-2017-77](https://user-images.githubusercontent.com/2492510/33220923-ec41a102-d100-11e7-96ea-e6d4e4ff59b0.jpg)
