### ISSUE TITLE
Hackable Signs: Session and Schedule

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#34]
### Description:
Design empty template signs for session hosts to make a sign for their session.

This year we may want to try the idea of having a hackable schedule poster like a whiteboard behind the information desk for additional information. It can be empty blocks for wranglers or info booth volunteers to fill in if it is useful.
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/2492510/29840716-c522ab80-8cb7-11e7-8928-fed92a5a24ba.png">

**Format**
- Double Sided
- Last year: https://github.com/MozillaFoundation/Mozfest2016_production/issues/92
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/2492510/29840854-3be3eb30-8cb8-11e7-854e-b927d4a64547.png">

### Previous Applications
![mozfest-documentation-session-cards](https://cloud.githubusercontent.com/assets/2492510/20152305/9b3aab0a-a672-11e6-9fb3-19d6c2297954.png)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLb3Q1bW9YMXVtcDQ
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/92

__________________________
#### Deadline
GanttStart: 2017-10-02
GanttDue: 2017-10-06

**Comment by brettgaylor** [comment]
Hey @sabrinang!  Just a reminder to ping us here when these are ready as we'd like to remix them to print out in the privacy space.

**Comment by sabrinang** [comment]
@marcwalsh What format do you think we should print these session signs? Will they be double sided on card stock again (half of an A4 size or A4)? I was wondering also how these are printed do we have to choose one design or can each space have it's own see redpen here: https://redpen.io/p/wy9faed9516e0af98f

@edrushka any design feedback?

**Comment by marcwalsh** [comment]
@sabrinang - let’s go for half A4

I think what would be easiest is a single sided A4 sheet which is then folded. That way we can use the same as Pixart posters (for D&D speakers etc) but I’ll change the paper weight.

We could use this as the same concept for the science fair also? What do you think @edrushka

**Comment by edrushka** [comment]
Single-sided A4 with a fold so it's the same on both sides works for me.
And yes, let's use same design for Science Fair.

**Comment by sabrinang** [comment]
@edrushka Updated redpen with folded versions: https://redpen.io/p/wy9faed9516e0af98f
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2492510/31708044-cdacf4b0-b3a2-11e7-8d16-8f952eb7d8c5.png">

@marcwalsh Here is the .pdf for the single side fold session sign
(no bleed): https://drive.google.com/open?id=0B4Q8pzCpDS_eZmhoN1VRaUR1U3c
(3mm bleed): https://drive.google.com/open?id=0B4Q8pzCpDS_eNDRBVHJIVjYxMUU

Any other .pdf for session signs are here: https://drive.google.com/open?id=0B4Q8pzCpDS_eaF95QUpKdTlDWDQ

**Comment by marcwalsh** [comment]
@sabrinang - template is below :)
[A4-Pixart-Poster.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1396591/A4-Pixart-Poster.pdf)

**Comment by taisdesouzalessa** [comment]
UPDATE: Sabrina answered this question. I won't export it with any marks. 
~~@marcwalsh I am fitting those layouts into the template. I am using the template guidelines as a reference so I know where things will be cut but I shouldn't add crop marks into the final PDF, correct? Just double checking~~

**Comment by taisdesouzalessa** [comment]
@marcwalsh the PDF you linked there seems to have A3 specs - 29.7 cm (width) x 42 cm (height). I am assuming we are printing it in A4 (21 x 29.7 cm) - I double checked with @sabrinang - and the template should be this one instead?

[pixartprinting-template-small-format-indoor-posters.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1403322/pixartprinting-template-small-format-indoor-posters.pdf)

I just wanted to flag it to make sure I am exporting the files in the right size.

**Comment by taisdesouzalessa** [comment]
@marcwalsh I exported the PDFs using the template I linked above (for A4). Please let me know if they are ok and if you need anything else :).

Flat posters: https://drive.google.com/file/d/0B3b1KWRwjxtoN3Q5S3Naa2oza1E/view?usp=sharing

Signs to fold: https://drive.google.com/file/d/0B3b1KWRwjxtoTXVBNTNObmZNYlU/view?usp=sharing

**Comment by marcwalsh** [comment]
Sent to Printers - ETA Wed 25th

(I've got generic and space signage for the folding options, and just generic signage for A4 due to pricing.)

**Comment by sabrinang** [comment]
## Post MozFest Documentation
The folded hackable signs were used at the demo
![mozilla-festival-2017-84](https://user-images.githubusercontent.com/2492510/33101870-fcae9826-cece-11e7-8fbe-161a500237bd.jpg)
The full A4 signs were more versatile to write more for sessions
![mozilla-festival-2017-270](https://user-images.githubusercontent.com/2492510/33101761-72c0514a-cece-11e7-8f1e-a5249f277b88.jpg)

I loved that the decentralization space stuck on a white layer to make whiteboard markers work on these signs. If it is cost efficient I would like to do this more broadly for hackable schedules.
![mozilla-festival-2017-243](https://user-images.githubusercontent.com/2492510/33101719-3e93e4d6-cece-11e7-9381-5dc4c3a9c8c4.jpg)
![mozilla-festival-2017-245](https://user-images.githubusercontent.com/2492510/33101727-46870614-cece-11e7-845a-3bfcdfceba27.jpg)

We did not get to it this year but a hackable schedule poster or white board would get utilized. A few spaces made there own analog overview of session schedules and they were very useful at a glance once you entered the space. Can white board posters be printed or is it only a layer we add on top afterwards?
![mozilla-festival-2017-247](https://user-images.githubusercontent.com/2492510/33101733-4bed2c00-cece-11e7-9a75-0162587506eb.jpg)
![mozilla-festival-2017-255](https://user-images.githubusercontent.com/2492510/33101752-67776774-cece-11e7-9a0e-1a438cc95f43.jpg)
![mozilla-festival-2017-244](https://user-images.githubusercontent.com/2492510/33101723-430d3634-cece-11e7-9116-fab4b2f64f3d.jpg)
![mozilla-festival-2017-277](https://user-images.githubusercontent.com/2492510/33101776-817764d0-cece-11e7-8ffb-b6881ae3cf20.jpg)
