### ISSUE TITLE
Poster: MozFest Tagline Poster (L10n and Hackable Versions)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#36]
### Description:
Design official MozFest Tagline posters that will be around the building and collect them at the end of the event for people to take them home. This year we will have one l10n poster (instead of 1 for each language) and a hackable poster for people to interact with. The concept of the l10n poster may be hackable too. The hackable posters needed to be lined with thick tape for pen ink not to bleed through to the walls. Various coloured sharpies were clipped to the hackable posters so attendees could write on them.

**Format and Quantity**
- [x] Main (EN) Poster
- [x] L10n Poster
- [x] Hackable Poster
- Let's print at external printers so we don't need to trim them at Ravensbourne

### Previous Applications
![mozfest-documentation-festival-posters](https://cloud.githubusercontent.com/assets/2492510/20196080/edec8cde-a74d-11e6-8a24-ddbaf699910c.png)

### Related L10N Issue:
https://github.com/mozilla/mozillafestival.org/issues/690
This year we want to put the multiple languages on one poster instead of having each on multiple. 
   de  German
   es  Spanish
   fr  French
   it  Italian
   hi-IN  Hindi
   pt-BR  Portuguese  
   zh-TW  Taiwanese

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLZjNELUpLcFZzeHc
https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eblZYMEpCcWQ1dDA
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/96
__________________________
#### Deadline
GanttStart: 2017-09-25
GanttDue: 2017-09-29

**Comment by sabrinang** [comment]
@edrushka Can you review this content and submit this l10n poster for content review as well? https://redpen.io/ufbe29f9afa00df975
<img width="360" alt="image" src="https://user-images.githubusercontent.com/2492510/31185127-0dc3855a-a8e0-11e7-9415-f49105f8da78.png">

**Comment by sabrinang** [comment]
note to self: double check with translations before exporting.

**Comment by marcwalsh** [comment]
Templates are here for A2 / A3: 

[A2 Poster Template](https://github.com/MozillaFoundation/mozfest-design-2017/files/1396602/pixartprinting-template-small-format-indoor-posters-3.pdf)

[A3 Poster Template](https://github.com/MozillaFoundation/mozfest-design-2017/files/1396600/A3-Pixart-Poster.pdf)

**Comment by marcwalsh** [comment]
Just want to confirm if @edrushka gave R+ to the localised versions of these. 

If so @sabrinang - feel free to export and I can send them separately to the hackable versions to print.

**Comment by sabrinang** [comment]
@edrushka Please review redpen for the web for all posters (main & hackable): https://redpen.io/p/zg7e998388cbc3dc47
<img width="751" alt="image" src="https://user-images.githubusercontent.com/2492510/31866399-b9106d90-b733-11e7-9628-90810c1db67e.png">


@marcwalsh Print .pdf for Pixart A2 & A3 exported here (you can find the l10n one there): https://drive.google.com/open?id=0B4Q8pzCpDS_ea1M2M0NlbERTVVk
Note: The A3 template attached above is actually an A4 but used another so it should be correctly exported as A3.

**Comment by edrushka** [comment]
The localized version is R+ (we didn't hear back from every language, but moving forward on assumption they are correct).

R+ on main and hackable as well. 

These look great as a set 💟

**Comment by sabrinang** [comment]
👍 All 3 are ready to print @marcwalsh 
Print .pdfs: https://drive.google.com/open?id=0B4Q8pzCpDS_ea1M2M0NlbERTVVk

**Comment by marcwalsh** [comment]
Sent to print! :D 💃

**Comment by sabrinang** [comment]
## Post MozFest Documentation

These posters were printed on thick glossy paper on A2 + A3 sizes. These posters added additional branding on cohesion to the space.
![mozilla-festival-2017-75](https://user-images.githubusercontent.com/2492510/33100669-0ec0d376-ceca-11e7-9542-05d816b17bba.jpg)
![mozilla-festival-2017-272](https://user-images.githubusercontent.com/2492510/33100602-db6a3cec-cec9-11e7-9f29-bf11c031d9c3.jpg)

The paper was thick enough for sharpie writing. Session hosts pasted their session on these though so that was an interesting use case. I'm unsure about the hackable posters this year the only ones I saw hacked up was by the volunteers after I let them know we wanted to encourage people to write on them and show people they are hackable. When we had a pile to give out at the end of MozFest they seem the least popular as well - we may consider not needing hackable posters next year.
![mozilla-festival-2017-234](https://user-images.githubusercontent.com/2492510/33100634-eee9fd34-cec9-11e7-92e7-8da464984948.jpg)
![mozilla-festival-2017-252](https://user-images.githubusercontent.com/2492510/33100740-6c38eeb2-ceca-11e7-80f2-ff1efe3d4be7.jpg)

Stephen and Jonathan did a great job finding places for these posters and they brought some life outside placing these on the exterior walls and rotating entrance!
![mozilla-festival-2017-226](https://user-images.githubusercontent.com/2492510/33100911-f2e26ad8-ceca-11e7-8173-b0c90b685255.jpg)
![mozilla-festival-2017-227](https://user-images.githubusercontent.com/2492510/33100642-f3f99b54-cec9-11e7-8546-b7ca2f090456.jpg)
![mozilla-festival-2017-228](https://user-images.githubusercontent.com/2492510/33100649-fa2e31a6-cec9-11e7-8796-0fecf423ac18.jpg)

![20171027-mozfest-signage-18](https://user-images.githubusercontent.com/2492510/33100702-3f0e1be2-ceca-11e7-81d8-c715779fef5d.jpg)
![20171027-mozfest-signage-22](https://user-images.githubusercontent.com/2492510/33100703-3f4080dc-ceca-11e7-9417-454f29d2e041.jpg)
