### ISSUE TITLE
Poster: Photo & Video Consent

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#38]
### Description:
Poster that outlines our photo consent policy. This is displayed prominently at registration, near the debates and discussion room and near the mains stage area.

**Format**
- A2 and A3?
- MozFest House Format: a smaller version that is branded mozfest house on registration table (sandwich board style: https://www.pixartprinting.co.uk/displays/point-of-sale-displays/floor-display/)

### Blocked by
We need to confirm copy and colour of lanyards.

### Previous Applications
The privacy alert posters were placed behind the registration table, in the Dialogues and Debates area in the Walker Space on level 0 and on level 4 in the Big Space.
![mozfest-documentation-privacy-alert](https://cloud.githubusercontent.com/assets/2492510/20195148/2bf62570-a74a-11e6-883a-86058c76cd4b.png)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_edk5HSmx6TmFHR0k
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/97

__________________________
#### Deadline
GanttStart: 2017-09-18
GanttDue: 2017-09-22

**Comment by marcwalsh** [comment]
@sabrinang I think A2 would work best as there is a fair amount of info, but we can always get a few A3 printed as well for smaller areas.

**Comment by sabrinang** [comment]
Revised the poster based on #45 lanyard colours and #21 name card id.
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/2492510/30929422-5a73a10e-a373-11e7-8de3-afa7c183e1aa.png">

@edrushka Can you review that the content is ok unchanged from last year? You can leave any content/design feedback on redpen here: https://redpen.io/at274005c111a37461

Working from last year's document, it set as A1 format so I will export A1, A2, A3 pdf just in case we need various sizes: https://drive.google.com/open?id=0B4Q8pzCpDS_eV1NQR3c4aFNMdzQ

**Comment by sabrinang** [comment]
Note: Make a version for MozFest House

The format for this will be a smaller version that is branded mozfest house on registration table (sandwich board style: https://www.pixartprinting.co.uk/displays/point-of-sale-displays/floor-display/)

**Comment by edrushka** [comment]
R+ content has not changed from last year and design looks good.

**Comment by sabrinang** [comment]
@edrushka I'm just working on exporting the mozfest house version and realized that the content of text needs to be different since it mentions specific Ravensbourne places for video do you have this content?
<img width="792" alt="image" src="https://user-images.githubusercontent.com/2492510/31242568-4d42bd68-a9bc-11e7-87f7-bc91bff2ae5d.png">

**Comment by edrushka** [comment]
Good catch @sabrinang!! 👀  @Saallen @lucieclick @marcwalsh please let us know what RSA/House text should be.

**Comment by lucieclick** [comment]
Hi - as far as I'm aware no sessions are being videoed but to cover us we could put the below and keep it more generic?

"Some stage activity in the Great Room might be captured on video. If you do not wish to be filmed, please sit at the back of this space" 

Then at the bottom
'Please visit the Welcome Desk for further information"

@marcwalsh @Saallen what do you think?

**Comment by Saallen** [comment]
Perfect Lucie
However Erika will you be contracting Dosed to do something on Thursday or
Friday?

**Comment by edrushka** [comment]
Not sure. Temi isn't meeting w/Dosed until next week. I don't know Dosed's schedule so can't say what day they'll be at the RSA. We can specify that they just shoot staff/volunteers/the building/the back of people's heads for the pre-week if required.  cc @tlasadea

**Comment by tlasadea** [comment]
@erika @sabrinang @lucieclick When I speak to Dosed I'll ask them if they have time to shoot anything on Thursday/Friday, and if so what that cost will be. It may be that we don't need it depending on the vision for the promo video 2018 - but think the copy that was suggested is above should suffice!

**Comment by edrushka** [comment]
Final copy suggestions:
- first paragraph keep the same
- second paragraph:
Please be aware that cameras maybe be present throughout the venue during the week. If you do not wish to be filmed, we advise you to clearly display your yellow lanyard and not sit in the front row.
- third paragraph 
Please visit the welcome desk for further information.

**Comment by Saallen** [comment]
one edit on:
Please be aware that cameras maybe be present throughout the venue during the week. If you do not wish to be filmed, we advise you to clearly display your yellow lanyard and not sit in the front row.

**Comment by sabrinang** [comment]
Copy has been updated for Mozilla Festival House poster: https://redpen.io/p/xrcc964c0113b22f73

Print .pdfs here (A1, A2, A3): https://drive.google.com/open?id=0B4Q8pzCpDS_eTmgzWXQ2ODVkQlk

@edrushka Can you give a final design/content review?

**Comment by edrushka** [comment]
~~R+ on house poster design and content!~~

**Comment by edrushka** [comment]
Dang it! Right after I wrote that I found a typo that is Sarah and I's fault. Sorry. Noted it in the redpen.

**Comment by sabrinang** [comment]
Typo corrected from "maybe be" to "may be": https://redpen.io/okb10313a99caa788c and print .pdfs updated (A1, A2, A3): https://drive.google.com/open?id=0B4Q8pzCpDS_eTmgzWXQ2ODVkQlk

@edrushka Can you review?

**Comment by edrushka** [comment]
R+ for real. Thanks for fixing.

**Comment by sabrinang** [comment]
Print .pdfs (A1, A2, A3) here: https://drive.google.com/open?id=0B4Q8pzCpDS_eTmgzWXQ2ODVkQlk

@marcwalsh These are ready for print

**Comment by marcwalsh** [comment]
@sabrinang thanks for this. For MozFest House we're getting the freestanding version so it's 100mm x 70mm which isn't a standard 'A' paper size. Would you be able to resize this? I'll get the Festival ordered :)

**Comment by marcwalsh** [comment]
@sabrinang - The guides are incorrect for Pixart 

Templates are attached below:
[A1-Pixart-Template.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1376987/A1-Pixart-Template.pdf)
[A2-Pixart-Template.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1376988/A2-Pixart-Template.pdf)
[A3-Pixart-Template.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1376989/A3-Pixart-Template.pdf)

**Comment by sabrinang** [comment]
Exports for Pixart: https://drive.google.com/open?id=0B4Q8pzCpDS_eWGl2U0N6cEtKcFU

**Comment by marcwalsh** [comment]
Sent to print!

**Comment by sabrinang** [comment]
## Post MozFest House Documentation
By the registration table, the privacy alert sign is a sandwich board that is seen near the corresponding lanyards so participants understand what they signify upon arrival and signup.
![mozfest-house-25](https://user-images.githubusercontent.com/2492510/32525022-5ef82cd4-c3d7-11e7-9884-374eaca7c1bb.jpg)
![mozfest-house-28](https://user-images.githubusercontent.com/2492510/32525024-64bc24a4-c3d7-11e7-9a68-1dfb6e99e801.jpg)

**Comment by sabrinang** [comment]
## Post Mozfest Documentation
Large cardboard signs were found near registration and in front of the table. I think one of the signs were suppose to be near the stages area but I'm unsure if they were.
![mozilla-festival-2017-192](https://user-images.githubusercontent.com/2492510/33099297-4db39a14-cec5-11e7-9f57-cb6bb3c3c374.jpg)
![mozilla-festival-2017-187](https://user-images.githubusercontent.com/2492510/33099287-4777bfae-cec5-11e7-88f3-a46b8673b533.jpg)
![20171027-mozfest-86](https://user-images.githubusercontent.com/2492510/33099375-8d8d1b6a-cec5-11e7-80ed-2e3f055bc0fe.jpg)
