### ISSUE TITLE
Poster: Participation Guidelines

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#41]
### Description:
Poster that outlines our participation guideline policy. This is displayed prominently at registration, info booths and throughout the space.

**Content**
Since this language will be seen on the back of the festival guide, the content can be found here: https://github.com/mozilla/mozillafestival.org/issues/703
These guidelines will be localized in other languages as well so this poster should accommodate more than English or if there are too many languages then we may need to separate posters.

**Format**
- A2 and A3? (can be the same as photo consent posters #38)

### Previous Applications
Originally it was on the back of the festival guide with a last minute request for it to be printed separately so it can be redistributed around:
![mozfest-documentation-participation-guidelines](https://cloud.githubusercontent.com/assets/2492510/20194548/8eeb7da4-a747-11e6-8be8-7c8cc9e2dc67.png)

### Related L10N Ticket
https://github.com/mozilla/mozillafestival.org/issues/731

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLcXFjTk5meXV5WkE
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/223

__________________________
#### Deadline
GanttStart: 2017-09-18
GanttDue: 2017-09-22

**Comment by sabrinang** [comment]
@edrushka Do you have anymore thoughts on the localized format of this participation poster.  
Are the seven languages all separate posters or together in a single poster? 
Are they the same size as the EN one (which I am thinking large like the photo/video consent poster size but last year it was just printed on letter sized paper since it was a last minute addition)? 

Related L10N ticket: https://github.com/mozilla/mozillafestival.org/issues/731

**Comment by edrushka** [comment]
The seven additional languages should all be on separate, individual posters. We do not need to combine them on a single poster.

@marcwalsh what size do we want these localized posters? I feel like paper-sized (A3) will be sufficient.

**Comment by edrushka** [comment]
Sabrina and I chatted and agreed:
- English should be on its own (we're thinking A3)
- All other languages can be on individual A4s but knowing we'll likely group these together, we can also put all seven on a single A1.
- Another option that will be more costly but could be really effective along the bathroom walls is a horizontal poster banner with each of the seven languages side by side.
@marcwalsh what do you think? we need to give Sabrina dimensions.

**Comment by sabrinang** [comment]
Note: Make a version for MozFest House

The format for this will be a smaller version that is branded mozfest house on registration table (sandwich board style: https://www.pixartprinting.co.uk/displays/point-of-sale-displays/floor-display/)

@edrushka Will this be in English only for MozFest House or all?

**Comment by edrushka** [comment]
English only for MozFest House. We are not localizing any of the House assets this year 😌

**Comment by sabrinang** [comment]
WIP (in progress resolving HI copy/paste issues) redpen iteration of A3 (EN) and A4 (all languages) versions: https://redpen.io/p/st123a285766334577

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/2492510/31100600-f3e90662-a77e-11e7-8deb-93acefe1f5d3.png">

**Comment by edrushka** [comment]
@TheoChevalier localized Participation Guideline posters are ready for QA here: https://redpen.io/p/st123a285766334577

**Comment by sabrinang** [comment]
HI design updated https://redpen.io/p/st123a285766334577 and ready for l10n review @edrushka

**Comment by sabrinang** [comment]
ES and ZH-TW has been revised on redpen: https://redpen.io/p/st123a285766334577

@edrushka Can you let me know when the l10n review is finished so we can prepare for print?

**Comment by edrushka** [comment]
If there are no other comments on the redpen let's go to print cc @TheoChevalier

**Comment by TheoChevalier** [comment]
Everything looks good on my side 👍

**Comment by sabrinang** [comment]
Thank you for the reviews!

.pdfs on Gdrive folder (MozFest A3, MozFest House A3 and MozFest all languages A4): https://drive.google.com/open?id=0B4Q8pzCpDS_eMEhYZEN5WGYwc1E

@marcwalsh These are ready for print

**Comment by marcwalsh** [comment]
@sabrinang - Sorry the guidelines on this are incorrect for Pixart. 

**See the templates below:**
[A4-Pixart-Template.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1376980/A4-Pixart-Template.pdf)
[A3-Pixart-Template.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1376981/A3-Pixart-Template.pdf)

**Comment by sabrinang** [comment]
Exports for Pixart: https://drive.google.com/open?id=0B4Q8pzCpDS_eR2NXM0E0TUlQR2s

**Comment by marcwalsh** [comment]
Sent to Print!

**Comment by sabrinang** [comment]
## Post MozFest House Documentation

Participation EN guides sandwich boards were seen on the registration table ![mozfest-house-23](https://user-images.githubusercontent.com/2492510/32524145-335a5da8-c3d3-11e7-85cc-2a080e18086b.jpg)
![mozfest-house-39](https://user-images.githubusercontent.com/2492510/33098743-4fd04d76-cec3-11e7-9eb4-a5ea6dbd0f50.jpg)

**Comment by edrushka** [comment]
Note that A4 did not print nicely on the cardboard. The ink bled a bit and logo was blurry and we had to reprint on A3. Still like cardboard as a more environmentally-friendly alternative to foam-core, but should be A3 or larger.

**Comment by sabrinang** [comment]
## Post MozFest Documentation 
These were found near registration in various languages flat on the table. Guideline sets were also found in the hallways of the washrooms. The cardboard printing came out a bit blurry this time so the untrimmed paper versions were reprinted.
![mozilla-festival-2017-214](https://user-images.githubusercontent.com/2492510/33098332-e2a88a2a-cec1-11e7-83df-b73cc4a12712.jpg)
![mozilla-festival-2017-193](https://user-images.githubusercontent.com/2492510/33098366-07a6e4a2-cec2-11e7-9128-82994a3b1ff5.jpg)
![mozilla-festival-2017-188](https://user-images.githubusercontent.com/2492510/33098377-0f966ff2-cec2-11e7-90d3-95283f088888.jpg)
