### ISSUE TITLE
Swag: Volunteer T-Shirts

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#42]
### Description:
Design t-shirts for our lovely volunteers so they can be easily spotted by attendees. The front of the shirt may contain this years branding and tagline. The back will have the #MozFest and it has been preferred to have the date present (example: MozFest 2017 or Mozilla Festival 2017) as it is seen as a collectable by volunteers. :) 

**MozFest House:** The volunteers will be wearing these shirts as wayfinding as well.

### Format
- Mozilla Festival: Front and Back of T-shirt A4 size 
- Mozilla Festival House: Front of T-Shirt only and A4 size

### Previous Applications
![mozfest-documentation-volunteer-shirts](https://cloud.githubusercontent.com/assets/2492510/20159448/844e6c88-a695-11e6-9f8d-bcae695294e9.png)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B8D3YQVeWHo7WWRrbG5PXzBjSHM
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/81

__________________________
#### Deadline
GanttStart: 2017-09-04
GanttDue: 2017-09-08

**Comment by sabrinang** [comment]
@marcwalsh Is our t-shirt supplier [Xamax](http://www.xamax.co.uk/100-gildan-coloured-t-shirt-free-print-offer.html) again this year? I'll be looking at colours and wondering what brand/style/colour we are limited to and design from there.

**Comment by EsmeSimcox** [comment]
@sabrinang I have been looking into T-Shirts companies including Xamax. I have been getting quotes for:
- Single Colour A3 print on the back and Single Colour A4 print on the front
- Single Colour A3 print on the back and a Full Colour A4 print on the front
- Full Colour A3 print on the back and a Full Colour A4 print on the front
- Full Colour A3 print on the back and a Single colour A4 print on the front

I will send you the google document, where I'm collecting the prices and which companies I'm looking at.

**Comment by sabrinang** [comment]
Thanks for the dimensions @EsmeSimcox - Let me know if there is a particular brand of shirt these quotes are for (gildan, raglan, fotl etc.) so I can start looking at colour?

**Comment by EsmeSimcox** [comment]
@sabrinang I will have a look on their website tomorrow about which brand t-shirts the quotes are for and let you know. Yes - all the t-shirt companies who have got back to me can print on colour t-shirts

**Comment by EsmeSimcox** [comment]
@sabrinang for Xamax Clothing it will be on Gildan T-Shirts and for the other company, it will either be on Gildan, Stars or Stripes brand of t-shirt.

**Comment by marcwalsh** [comment]
Hey @sabrinang @EsmeSimcox - let's stick with Xamax this year.

Colour choices are below:

<img width="225" alt="screen shot 2017-09-08 at 15 44 22" src="https://user-images.githubusercontent.com/30226684/30216964-a7cb56c0-94ac-11e7-91b8-66cb70b68d7d.png">
<img width="225" alt="screen shot 2017-09-08 at 15 44 14" src="https://user-images.githubusercontent.com/30226684/30216967-a7e86cc4-94ac-11e7-919f-4913301efc53.png">
<img width="222" alt="screen shot 2017-09-08 at 15 43 58" src="https://user-images.githubusercontent.com/30226684/30216968-a7eaae9e-94ac-11e7-8529-5b0eac7a293f.png">
<img width="223" alt="screen shot 2017-09-08 at 15 43 49" src="https://user-images.githubusercontent.com/30226684/30216969-a8a6e92e-94ac-11e7-9a38-a48ae3be0ff9.png">

**Comment by EsmeSimcox** [comment]
Hi @ZiggyMaes @tomfarrow @rtsayles, @sabrinang is beginning to look at colour for T-Shirts and I thought I would tag you in so you can be involved. Also please reference #49 as the colour of the t-shirt will need be as close to the pallet as possible.

**Comment by sabrinang** [comment]
Matching some t-shirt colours that are close to our palette and pairing it with (single colour) designs. Inital T-shirt mockups are on redpen: https://redpen.io/p/rveb958102a79887bb
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/2492510/30287208-1780a1c2-96d9-11e7-8f13-2429cf58f774.png">

**Comment by sabrinang** [comment]
Looking at the tshirt palette available, it looks like we are going with the [Gildan Softstyle® Adult T-Shirt](https://www.xamax.co.uk/gildan-softstyler-adult-t-shirt.html)

**Comment by EsmeSimcox** [comment]
@sabrinang These look amazing! My favourite is the blue one on the bottom right, but I love them all!

**Comment by tad124737337** [comment]
I'm with Esme on the bottom right!
Also a fan of the blue in the top left. Not a fan of the yellow or red at all.

Bottom right > top left > top right > bottom left for me

**Comment by tad124737337** [comment]
Will the aqua perhaps look a little odd with the aqua name badges on top, actually?

**Comment by sabrinang** [comment]
@TomFarrow  I iterated on the the design for name cards and they will have more of the deep bue-puple with bits of aqua so it shouldn't look to matchy if you are concerned about that

**Comment by tad124737337** [comment]
@sabrinang sounds great! :)
I like the royal blue

**Comment by sabrinang** [comment]
@edrushka  I’m finalizing these t-shirts can you design review??
Mozilla Festival Volunteer Shirt: https://redpen.io/fg78b930420def5ec8
Mozilla Festival House Volunteer Shirt (I believe we are doing front print only): https://redpen.io/rmb5ffa2b16fe016b0

**Comment by edrushka** [comment]
Done. @Saallen pls review.

**Comment by Saallen** [comment]
Hey the volunteers in MozFest house will all be boys-and I think they might not like the pink- is there another option? @sabrinang

**Comment by marcwalsh** [comment]
@Saallen - We just talked in the design catch up and the colour scheme for the pink and orange is the colour scheme. So the pink tshirts and the orange name cards match this. :)

**Comment by marcwalsh** [comment]
I also love pink <3

**Comment by tad124737337** [comment]
The pink looks really good for this!!

**Comment by Saallen** [comment]
If the ppl wearing the tee shirts are happy to wear pink - then fine by me
@TomFarrow are you ok with the colour of the MozFest house teeshirt?

**Comment by Saallen** [comment]
cool- @TomFarrow  seems in agreement- go for it

**Comment by tad124737337** [comment]
Yes!!!!

**Comment by sabrinang** [comment]
Redpen updated with final design: https://redpen.io/fa4f20de66852a74ab

![mozilla festival house volunteer shirts](https://user-images.githubusercontent.com/2492510/31297862-7a9dbef8-aa9c-11e7-9add-cb8a0375c38a.jpg)

T-Shirt colours: Antique Heliconia & Antique Jade Dome
<img width="141" alt="image" src="https://user-images.githubusercontent.com/2492510/31297930-b76713c0-aa9c-11e7-904a-875f1d1a9e1f.png">

.eps files of Single Colour (white) A4 designs (MozFest Front + Back / MozFest House Front Only) and exported here: https://drive.google.com/open?id=0B4Q8pzCpDS_eSlFrcFVLUnlzLVE

.ai file of all t-shirt designs are here: https://drive.google.com/open?id=0B4Q8pzCpDS_eSUhZMUZjU0ZRWlE

Thank you for the feedback!

**Comment by sabrinang** [comment]
@marcwalsh this is ready for print!

**Comment by marcwalsh** [comment]
Sent to Printers:

House - ETA: 19th October
Festival - ETA: 24th October

**Comment by sabrinang** [comment]
## Post MozFest House Documentation

The shirts helped identify volunteers easily and expressed the brand palette in a vibrant way
![mozfest-house-42](https://user-images.githubusercontent.com/2492510/32522777-86ffb292-c3cd-11e7-9c8d-3bd30a3cd6b6.jpg)

## Post MozFest Documentation

Initially the MozHelp shirts were teal but on the Thursday before the festival (Oct 19), Marc was notified to change the colour of the tshirt for the weekend because the tshirt company got in touch with him that morning to let him know they run out of large and won’t get them in stock until December. Since we kept the shirt design in white it was easy to go with red which was one of the other previous options. The red was easy to spot and name tags had good contrast on them as well. I also revised MozHelp signs to be red to match the volunteers.

Thanks FuzzyFox for being my t-shirt model throughout the weekend!
![mozilla-festival-2017-289](https://user-images.githubusercontent.com/2492510/32968683-f5e6af46-cb96-11e7-823c-6d52c99ac505.jpg)
![20171027-mozfest-114](https://user-images.githubusercontent.com/2492510/32968722-1df89792-cb97-11e7-9b3e-cf7a3bb1fbf0.jpg)
![20171027-mozfest-221](https://user-images.githubusercontent.com/2492510/32968723-1e0f7f52-cb97-11e7-9716-8bdfe6bec7f9.jpg)

**Comment by edrushka** [comment]
Note for 2018 ordering: volunteers need more than one t-shirt if working multiple days (no time for laundry).
