### ISSUE TITLE
Swag: Festival Guide

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#43]
### Description:
The festival guide is a key part and informative part of the MozFest swag. Last year's festival guide came in a clipped package including:
- festival guide
- wrangler bios
- floor map
- notebook
- sharpie + clip

**Format:**
This year we can decide on a format that works with the swag. Swag TBD

### Content
All content here: https://github.com/mozilla/mozillafestival.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22Festival+Guide%22

### Previous Applications
![artboard jpg](https://cloud.githubusercontent.com/assets/1068783/20194991/946393aa-a749-11e6-9fb0-050aa4cd7fef.png)

### Related Issue
Notebook? #44
Swag?

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLejJsNlI2UmJjVGs
Github Issues
concept: https://github.com/MozillaFoundation/Mozfest2016_production/issues/69
version 1 + 2: https://github.com/MozillaFoundation/Mozfest2016_production/issues/135
final version: https://github.com/MozillaFoundation/Mozfest2016_production/issues/136
production: https://github.com/MozillaFoundation/Mozfest2016_production/issues/39

__________________________
#### Deadline
GanttStart: 2017-09-04
GanttDue: 2017-10-02

**Comment by cassiemc** [comment]
@edrushka @sabrinang Can you assign this to me please (and any other issues as necessary)?

**Comment by sabrinang** [comment]
@cassiemc I tried assigning this to you but I'm not able to, I think you need accept to be a collaborator first: https://github.com/MozillaFoundation/mozfest-design-2017/invitations

**Comment by cassiemc** [comment]
@sabrinang I accepted the invite, had to enable 2FA. Thanks!

**Comment by cassiemc** [comment]
I've sent @marcwalsh an email but it bounced back to me, so adding it here. Hopefully we can get this quote request out soon and get some answers back from the printer to make decisions around size. :) cc @edrushka @sabrinang @Saallen 

I think this is a fair representation of what we discussed this morning but please feel free to add to or adjust when you send to the printer. I always like to leave it open to their recommendations as well – I think printers like when you treat them as knowledgeable collaborators! – but I know you have worked with them many times prior so trust your judgment :) Let me know if you have any questions!


Note: Please see attached image for reference. Assembly of all separate pieces would happen on our end


## Piece 1: Festival guide booklet [Fig. 1]

**Size**: A5, portrait orientation (148mm x 210)

**Extras** (please quote separately for these, if possible)
* Built-in folder on the left hand side of the cover about 1/3 the height of the page, or whatever you suggest if there is a standard size or layout for this (doesn't have to be fancy) – see attached drawing
* Tabbed booklet – to have three tabs sticking out of the booklet for readers to quickly and easily find content. See the attached reference photo, but with just regular ink printed on them, not gold foil [Fig. 2]
* We may be interested in printing Braille on the front or back cover. Please let us know what this would be extra

**Paper** (please quote for these three weight combinations)
I'm referencing Lynx digital smooth paper (from a Lynx Opaque Ultra Smooth & Vellum book) but any comparable paper is fine. Please let us know if we need to use a heavier stock cover paper to account for the folder or braille options
* 104 GSM Text / 176 GSM Cover (70lb smooth text matte + 65lb smooth cover matte)
* 104 GSM Text / 216 GSM Cover (70lb smooth text matte + 80lb smooth cover matte)
* 118 GSM Text / 216 GSM Cover (80lb smooth text matte + 80lb smooth cover matte

**Binding** (please quote for both)
* Staples
* Perfect

**Pages** (please quote for all #s)
* 12pp (plus front and back cover)
* 24pp (plus front and back cover)

**Printing method** (possible to quote for both?)
* Digital
* Litho / offset

**Quantity**
* @marcwalsh  can you insert # here

**Color**: Full colour throughout. Please quote for both if possible (realize it may not be an option to go without pantones on an offset press)
* With pantone matching
* Without pantone matching

## Piece 2: Separate, smaller multi-page booklet (w/ people & bios) [Fig. 3]

**Size:** 118mm x 175mm
* open to standardized options here as long as it is smaller than the guide booklet and would fit inside the pocket)

**Color** (please quote for both)
* Black and white on colored paper
* Full color on white paper

**Paper**
* 104 GSM Text (70lb smooth text matte) or comparable
Binding: staples
Pages (please quote for both)
* 12pp (incl. front and back cover)
* 20pp (incl. front and back cover)

**Printing method**: probably digital
**Quantity:** @marcwalsh  to insert #

## Piece 3: Map – Option A : Single page card stock insert [Fig. 4]

**Printer method:** digital or offset
**Quantity:** @marcwalsh  to insert #
**Size:** 118mm x 190mm portrait orientation
* Again open to standardized options as long as it would fit within the pocket, preference also to being the same width as the multi-page booklet above
Paper – matte, heavier weight e.g. 216 GSM (80lb)

**Colour:** full colour on one side (blank on the other side)

## Piece 3: Map – Option B: Trifold brochure-type insert  [Fig. 5]
**Printer method**: digital or offset
**Quantity**: Marc to insert #
**Size**: 190mm x 118mm folded (190mm x 354mm unfolded) portrait orientation
* Again open to standardized options as long as it would fit within the pocket, preference also to being the same width when folded as the multi-page booklet above

**Folds:** two; doesn't matter how they fold, whichever way is easiest
**Paper** – matte; open to lighter weight paper something like 148 GSM (100lb text)
**Color:** full color on both sides

Please contact Cassie McDaniel, cassie@janeandjury.com for any questions about design or these options.

![printer-options-mozfest-quote](https://user-images.githubusercontent.com/1186326/30502631-1833ee26-9a35-11e7-9bf4-7e5514271008.jpg)

**Comment by cassiemc** [comment]
Design progress is here: https://redpen.io/p/hc4986de6eb6952d0c

@sabrinang @edrushka Two revised cover options, with and without the lines, using the gradient mesh over the photo (I like this direction more than the prior iteration!) – [here without lines](https://redpen.io/sf5645db5c64a64cb1) and [here with lines](https://redpen.io/zxae36ca5307cfcd5e)

**Comment by cassiemc** [comment]
Fixed the covers with the correct lockup. @sabrinang @edrushka https://redpen.io/sf5645db5c64a64cb1 and https://redpen.io/zxae36ca5307cfcd5e

**Comment by sabrinang** [comment]
I downloaded files from dropbox: https://www.dropbox.com/sh/yzey1ftfhz7gnnp/AAB5WCPBMVAnZ_uG7NAyf3mZa?dl=0 and uploaded it to our drive as well here: https://drive.google.com/open?id=0B4Q8pzCpDS_eaVE4RWhndUFBcTQ

@cassiemc Before closing this ticket can you make sure that this is the correct, up-to-date files that I transferred to Google Drive? Just to make sure we can access these in the future and it is all in the Mozilla Festival 2017 folder with the other assets.

**Comment by marcwalsh** [comment]
Printed and Delivered - They look AMAZING! <3
