### ISSUE TITLE
Swag: Notebook

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#44]
### Description:
Handy dandy notebook swag for our attendees.

**Format:**
This may depend on the design of the #43 Festival Guide but last year we went with A6.

### Previous Applications
The A6 (10.5 x 14.8cm) notebooks are clipped to the festival guide/map accompanied with a sharpie. It has 60 pages of 90gsm ivory paper sewn bound with yellow thread.

![mozfest-documentation-notebook](https://cloud.githubusercontent.com/assets/2492510/20171926/c62eddf2-a6e7-11e6-80dc-7501d268687b.png)

### Related Issue
#43 Festival Guide

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B2irLVDJivhLejJsNlI2UmJjVGs
https://drive.google.com/open?id=0BzVQTTEXQZdXVXJlWHpLYTFfS0U

Github Issues: 
https://github.com/MozillaFoundation/Mozfest2016_production/issues/150
https://github.com/MozillaFoundation/Mozfest2016_production/issues/34
__________________________
#### Deadline
GanttStart: 2017-09-18
GanttDue: 2017-10-22

**Comment by sabrinang** [comment]
Thread-bound notebooks from Pixart: https://www.pixartprinting.co.uk/digital-litho-printing/office-products/customised-notebook/ 

The A6 template is on the page or you can download directly here (.ai/.eps/.psd): [717_388_8392.zip](https://github.com/MozillaFoundation/mozfest-design-2017/files/1363715/717_388_8392.zip)

Full color print on the outside and 90gsm ivory paper on the inside with 60 pages and sewn bound. 

@marcwalsh Can you confirm these are the notebook specs (same as last year) we are going with this year?

**Comment by sabrinang** [comment]
Cassie's redpen iterations here: https://redpen.io/p/pgca50618af5405c72

**Comment by marcwalsh** [comment]
@sabrinang @cassiemc - Let's go for A5!

[**Templates and Instructions**](https://github.com/MozillaFoundation/mozfest-design-2017/files/1371356/QFS_D_A5.zip) are attached here.

**There is also a choice of thread colours:**
<img width="680" alt="screen shot 2017-10-10 at 10 47 41" src="https://user-images.githubusercontent.com/30226684/31380190-85ef0c80-ada8-11e7-935e-bb070f72bb29.png">

**Comment by edrushka** [comment]
We all agree yellow would be great!

**Comment by cassiemc** [comment]
Updated the files to A5. Final redpen is here: https://redpen.io/tz398764f1d379b048
Final pdf is here: https://www.dropbox.com/s/iesb6iw4hx5hedn/Mozfest-Notebook-Print-ready-A5.pdf?dl=0
Final .ai source file is here: https://www.dropbox.com/s/j67r5puog8c8fz2/Mozfest-Notebook-Print-ready-A5.ai?dl=0
@marcwalsh yellow threading, please!

**Comment by sabrinang** [comment]
@marcwalsh Notebooks are ready for print 👍

**Comment by sabrinang** [comment]
@cassiemc I uploaded those dropbox files on to this gdrive folder as well: https://drive.google.com/open?id=0B4Q8pzCpDS_eWkF3R2UwaTE1T2c 

If you have any other notebook files feel free to upload them there as well!

**Comment by marcwalsh** [comment]
Sent to print! 📘💃❤️

ETA: 25th October

**Comment by sabrinang** [comment]
## Post Mozfest Documentation

Notebooks were available at the swag table and they are the same size as the festival guide this year. They had blank off-white pages and the cover ink wears off quite easily near the spine.
![mozilla-festival-2017-182](https://user-images.githubusercontent.com/2492510/33097952-92f8f63c-cec0-11e7-8802-33f1f6cc0bce.jpg)
![mozilla-festival-2017-183](https://user-images.githubusercontent.com/2492510/33097954-9311b5c8-cec0-11e7-9d80-90a8801312e4.jpg)
![20171027-mozfest-signage-16](https://user-images.githubusercontent.com/2492510/33098025-d5d4ba5e-cec0-11e7-96d5-7f490fb425d2.jpg)
