### ISSUE TITLE
Swag: Lanyard

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#45]
### Description:
Decide on the colour of the lanyard for attendees as well as a colour for attendees who do not want to be on video or photographed. 

**Format**
Last year, we had blue lanyards with 2-point metal swivel lobster clasp style clip were the main style. Yellow lanyards were used to indicate they did not want photo/video taken of them. Both lanyards have a safety release in the center.

### Previous Applications
![mozfest-documentation-lanyard](https://cloud.githubusercontent.com/assets/2492510/20187514/67839170-a729-11e6-957e-9cdb1deffde5.png)

### Reference from Last Year: 
Google Drive Files: n/a
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/36

__________________________
#### Deadline
GanttStart: 2017-09-04
GanttDue: 2017-09-08

**Comment by sabrinang** [comment]
@marcwalsh Who are the suppliers for these lanyards? I was wondering what colours they have to choose from

**Comment by marcwalsh** [comment]
@sabrinang - [Here's the link](https://www.aspinline.co.uk/lanyards/double-ended-lanyards/double-ended-lanyards-15mm-1-colour)

They are Pantone matched, however, I would try to avoid Neon as that can sometimes cost more.

**Comment by sabrinang** [comment]
![preview](https://user-images.githubusercontent.com/2492510/30890040-1ed51612-a2df-11e7-86f2-feaab650ae15.jpg)

PANTONE 2597 CP - purple
PANTONE 102 CP - yellow

**Comment by marcwalsh** [comment]
Sent to Printers!! 👯‍♂️
