### ISSUE TITLE
Swag Meta-Ticket

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2017#47]
This is the place for all things Swag. 

Currently planned are the following pieces:

- [x] Socks
- [x] A6 Notebook
- [x] Waterbottle
- [x] Sharpies

**Comment by cassiemc** [comment]
@marcwalsh How big is the drawstring bag?

**Comment by marcwalsh** [comment]
Hey @cassiemc - I think we're looking to remove the bag. I'll update the ticket now.

**Comment by cassiemc** [comment]
@marcwalsh ok thanks! I heard it was maybe a "grab what you want" swag table, is that what you're thinking, or how do you imagine will be organized? Just trying to think dimensions for the festival guide and it it can slot in with or clip together nicely with other swag, as per last year

**Comment by marcwalsh** [comment]
We’re looking at more a grab what you want section. I think we’re removing the bag and going with socks or equally out there. :)

For the festival guide, think of it as something a little separate, if you feel a notebook works in the clipped back just let me know and I’ll work it into costing! Don’t let the swag hold you back!


On 14 Sep 2017, at 16:04, Cassie McDaniel <notifications@github.com<mailto:notifications@github.com>> wrote:


@marcwalsh<https://github.com/marcwalsh> ok thanks! I heard it was maybe a "grab what you want" swag table, is that what you're thinking, or how do you imagine will be organized? Just trying to think dimensions for the festival guide and it it can slot in with or clip together nicely with other swag, as per last year

**Comment by sabrinang** [comment]
**2017 Swag** 

#53 Water Bottle
#51 Socks
#45 Lanyard + #21 Namecard #24 Namecard Stickers
#23 MozFest Stickers
#44 Notebook
#43 Festival Guide (has a back pocket to hold stuff)
#42 Volunteer T-shirt
#79 USB Flash Drive
webcam blocker stickers (sticker mule)

@marcwalsh Sharpies are in the description - have they been ordered?
