### ISSUE TITLE
Style Guide: Colour

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#49]
### Description:
Decide colours used for this year's MozFest. Align with evolving Mozilla wide palette, keeping it vibrant and include a variety the works with people who have colour vision deficiencies.  

**Format**
Include .ase file and document in style guide.

### Previous Applications
<img width="856" alt="image" src="https://user-images.githubusercontent.com/2492510/30127948-ceb1d9b6-92f5-11e7-8f60-15761cc7e70c.png">

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eRmVUZmlfVUYzT2M
Github Issue: MozillaFoundation/Mozfest2016_production#76

### Related to issue #7

**Comment by sabrinang** [comment]
**Palette**
We will be using tint and shade variants from our original palette and highlight 6 for spaces and using a mixed palette for overall mozfest design.
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/2492510/30128784-c0553216-92f8-11e7-840c-360e03ff4589.png">

**Accessibility and colour:**
Use iconography and text to accompany colour wayfinding where possible:
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/2492510/30128674-5fcd2dfe-92f8-11e7-81ed-549a9a38b915.png">

Selecting a range of colours overall that appears different across the spectrum of vision abilities and using patterns with problematic pairs is highly suggested for data visualizations or wayfinding without text or icons.
<img width="992" alt="image" src="https://user-images.githubusercontent.com/2492510/30128576-0593b02e-92f8-11e7-8c37-39eab21a4fd0.png">

See more colour blindness tips: http://blog.usabilla.com/how-to-design-for-color-blindness/

**Comment by sabrinang** [comment]
<img width="243" alt="image" src="https://user-images.githubusercontent.com/2492510/30129020-6ccb8be4-92f9-11e7-95b6-35d97da3cfbc.png">

Swatch File (.ase) is on the drive here: https://drive.google.com/open?id=0B4Q8pzCpDS_ed3U1SjlOWjBKWk0

**Comment by sabrinang** [comment]
Pantones are missing from this colour palette (will be matched and added soon).

**Comment by rtsayles** [comment]
@EsmeSimcox What are our options for colors?

**Comment by sabrinang** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2492510/30232413-d10be250-94a4-11e7-8bf3-811211e78ce3.png">
Matching colours using the PANTONE+ Colour Bridge Coated Book. However, I choose some from the Neon & Pastels book (which I don't have in person to match) as they are more vibrant.

![coatedbook](https://user-images.githubusercontent.com/2492510/30232596-bf092efe-94a5-11e7-867a-1a9951322112.jpg)

Swatch file (.ase) updated: https://drive.google.com/open?id=0B4Q8pzCpDS_eZWdNMlBkVVNoYkE
Style guide files (.ai/.pdf) updated to include pantone: https://drive.google.com/open?id=0B4Q8pzCpDS_eSjZ1QTVGM2lRaGM

**Comment by sabrinang** [comment]
@cassiemc Please check these pantones with the book you have, if they seem inaccurate please update them before using them in the festival guide.
