### ISSUE TITLE
Photo for MozFest House page

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/mozfest-design-2017#50]
We need a photo for the pre-week page. @Saallen what do you think of these? We don't have the rights them, though - we'd have to ask permission from the RSA to use.
![dsa-entrance1](https://user-images.githubusercontent.com/4515662/30303045-2a4cbd04-971a-11e7-858b-9d13480160d5.jpg)
![durham-street-auditorium--fixed-theatre-side-view1](https://user-images.githubusercontent.com/4515662/30303046-2c2238ac-971a-11e7-87ea-4fb34abddd53.jpg)

**Comment by edrushka** [comment]
Options from our own photos (that don't look quite so much like Ravensbourne):
https://www.flickr.com/photos/mozfest/22252821513/in/album-72157658649418943/
https://www.flickr.com/photos/mozfest/22847962796/in/album-72157658649418943/
https://www.flickr.com/photos/mozfest/22892317531/in/album-72157658649418943/

@Saallen  Do you have any links to Eric Westra's albums? They have a nice different feel to them that would be good for the House.

**Comment by Saallen** [comment]
Hey @edrushka and @lucieclick
I think we should use a picture of the entrance so when ppl see the entrance they recognise the building on the day. @lucieclick can you ask Kate if we can use one of their photos.

![image](https://user-images.githubusercontent.com/10194015/30326187-95e8d55c-97bf-11e7-9dce-4517ab58ff43.png)


![image](https://i.pinimg.com/236x/55/3e/78/553e7824e1416f72873b871a655dd2ed--john-adams-interior-exterior.jpg)

**Comment by edrushka** [comment]
@sabrinang could you turn any of these RSA entrance shots into a hero banner for the MozFest House page, or should we keep looking?

**Comment by sabrinang** [comment]
@edrushka These RSA entrance shots work (if you have links to higher res versions available that would be great or I'll try looking around online too)

**Comment by edrushka** [comment]
@lucieclick if the RSA gives us permission can you please see if they have a higher-res photo we can use?

**Comment by edrushka** [comment]
Here's the photo from the RSA (we have permission to use this one). @sabrinang can you apply a treatment to make it a hero banner for the page?

![rsa exterior close](https://user-images.githubusercontent.com/4515662/30391062-067cff98-986d-11e7-9f9e-0d4218abb14c.jpg)

**Comment by Saallen** [comment]
what really important in this picture is the RSA ON THE COLUMN.
Can we darken that so its seen?


Sarah Allen

Executive Festival Director, MozFest
Mozilla Foundation

Find out more about MozFest <https://mozillafestival.org/> and follow the
conversation on twitter <https://twitter.com/mozillafestival?lang=en-gb>

**Comment by sabrinang** [comment]
@erikad I added the colour treatment we have for hero banners to the approved image:
![rsa-banner](https://user-images.githubusercontent.com/2492510/30399776-a81a3782-9889-11e7-9364-d0ebc453f407.jpg)

I don't think image has been approved but it might not be best to have lots of text in the hero banner image area since a white heading title goes above it but I treated it with the colour as well:
![rsa-banner2](https://user-images.githubusercontent.com/2492510/30400428-b616c614-988b-11e7-8c06-ace17f0a257d.jpg)

@Saallen If this image is important for wayfinding and reference I highly suggest it goes in the body of the content itself and leave the hero banner mainly for colour/texture for visual interest.

**Comment by Saallen** [comment]
👍  @sabrinang

**Comment by Saallen** [comment]
Hey, we would like to use the hero banner also for ticketing pages- especially our co working sign up
https://ti.to/Mozilla/mozfest-house-co-working-space
Let me know when we can add - 💯

**Comment by Saallen** [comment]
Hey, we would like to use the hero banner also for ticketing pages- especially our co working sign up
https://ti.to/Mozilla/mozfest-house-co-working-space
Let me know when we can add - :

**Comment by sabrinang** [comment]
I made some logo options for the photos:
![rsa-banner-logo](https://user-images.githubusercontent.com/2492510/30932059-391798e6-a37b-11e7-82ac-7f21224698b9.jpg)
![rsa-banner2-logo](https://user-images.githubusercontent.com/2492510/30932058-39146c20-a37b-11e7-8dc9-bd4144e04726.jpg)

![rsa-banner-light2-logo](https://user-images.githubusercontent.com/2492510/30937924-2efae9fa-a38d-11e7-88eb-5239f4569aa8.jpg)

![rsa-bannerlight-logo](https://user-images.githubusercontent.com/2492510/30937631-3c760cdc-a38c-11e7-8add-52ad0dd0195e.jpg)


All banners with/without logos are here on gdrive with retina size versions: https://drive.google.com/open?id=0B4Q8pzCpDS_eZ3hvVFJjY1pWYnc

@Saallen or @edrushka Please close this ticket if the photos are reviewed and good to go

**Comment by Saallen** [comment]
Looks great @sabrinang - loving the 3rd one!
@lucieclick do we need to get RSA approval here?

**Comment by sabrinang** [comment]
@edrushka Is this issue complete?

**Comment by edrushka** [comment]
Yes. Closing.
