### ISSUE TITLE
Swag: MozFest Socks

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2017#51]
London is cold, so we need to keep out feet warm. 👠

There are two options for socks which are below:

1. Woven Socks (Cheapest option) - 4 week lead time
<img width="610" alt="screen shot 2017-09-12 at 17 22 56" src="https://user-images.githubusercontent.com/30226684/30337101-2e744918-97df-11e7-8023-e117fc9aa7fa.png">

2. Slipper Socks (Slightly more expensive, but more interesting) - 3 week lead time
<img width="613" alt="screen shot 2017-09-12 at 17 22 46" src="https://user-images.githubusercontent.com/30226684/30337213-7ad8844a-97df-11e7-80d8-6a61a672ba67.png">

@edrushka @sabrinang @Saallen @EsmeSimcox  - It would be great to have your feedback on this!

**Comment by edrushka** [comment]
The woven ones (option 1) could be super cool if we could use one of Sabrina's background patterns.

**Comment by sabrinang** [comment]
I like the 1 woven socks! I have had slipper socks with the puff ink grip and it was not as versatile since it is not meant to be worn in shoes (slightly uncomfortable if puffs are even, feels lumpy)

**Comment by EsmeSimcox** [comment]
I love the woven ones! I think they would be such a good SWAG item!

**Comment by marcwalsh** [comment]
So I've heard back from the printers and the woven socks are a bit too tight of a deadline. They would need the artwork next Wednesday at the moment, but I'll keep trying to push back. 


Example template is below:
[AND socks-3.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1306395/AND.socks-3.pdf)

**Comment by edrushka** [comment]
OK see what you can do, Marc. We have no other urgent, imminent deadlines, so it's possible we can do this if they can give us just a bit more time.

**Comment by sabrinang** [comment]
@marcwalsh Do you have the link to the promotional standard woven socks? I can't find more details and I want to know if there are any limitations and the format of the "printed header card" mentioned in the description. Are we also selecting one design?

I designed some sock ideas on redpen but unsure what is doable by the sock manufacturer: https://redpen.io/p/bnfe819bbfecaa5ede
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/2492510/30563220-15799094-9c76-11e7-9ab9-3706451f80b0.png">

**Comment by marcwalsh** [comment]
@sabrinang - I'll send the designs over and see what's possible.

The vendor is [Brand-Ahoy](http://www.brand-ahoy.co.uk/socks-ahoy)

It looks like on the docs they sent it's full printing, however some the details on the website says it's only in certain sections. I'll confirm first thing tomorrow UK time.

Here's some grabs from the website on what they offer.

**Print Areas:**
![imprint-sock-280x300](https://user-images.githubusercontent.com/30226684/30564923-793b1df8-9cbe-11e7-954e-205ece1fc035.jpg)

**Sock Colours**
![sock colours](https://user-images.githubusercontent.com/30226684/30564926-7ca04806-9cbe-11e7-9943-b174cbaa2f82.png)

**Printing/Thread Colours**
![sock ink colours](https://user-images.githubusercontent.com/30226684/30564932-7f3c45e2-9cbe-11e7-9c3b-cb8d93f4e966.png)

**Comment by sabrinang** [comment]
@marcwalsh These details look like it is for the slipper sock style not woven sock? but thanks for sending it over to see what is possible! I can rework it tomorrow to fit the printing areas and colours

**Comment by marcwalsh** [comment]
Hey @sabrinang - Great news they are able to meet the design of all the socks apart from the top right. I'm just confirming about a card that the socks come packaged in and will try and chat with @Saallen to get this signed off as I've got a total price etc now.

**Comment by marcwalsh** [comment]
Hey @sabrinang - This is all signed off now - I just need a couple of bits:

1 - We need 1 design choice out of these.
2 - Can I get a PDF version of this as well as the Pantone colours.
3 - They are also able to print a 6 x 13cm printed card to hold the pair together. It's folded in half, but this can just be an existing pattern rather than something specifically designed.

**Comment by sabrinang** [comment]
The coloured cube options are popular on redpen so they are the two designs exported in the pdf and I include a card pdf if it is needed in this gdrive folder here: https://drive.google.com/open?id=0B4Q8pzCpDS_eeXo1dzhkVmVVZkU

The pantone colours are in the pdf too (some are neon pantones so the yellow, cyan, pink are brighter - I can pick alternatives if neons are not available) 
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/2492510/30718003-647b3af8-9ed3-11e7-8886-b82f55736a4b.png">

**Comment by marcwalsh** [comment]
Amazing thanks @sabrinang - I’ll be sending these AM BST tomorrow so I would be good to have the non-neon Pantones as a backup just incase :)

**Comment by sabrinang** [comment]
I updated the folder which has a .pdf that contain 4 pages now (2 with neon pantones and 2 without)

**Comment by marcwalsh** [comment]
Thanks so much for getting this all together so quickly @sabrinang!

I'll close this as it's sent to the printers, I'll reopen if there are any issues.

**Comment by edrushka** [comment]
I am so excited about these socks! 👣
