### ISSUE TITLE
MozFest House Brand

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#52]
### Description:
For the pre-week, these spin-off, sister events will be called MozFest House. Let’s create a visual modifier that includes or adds the name “House” that could be easily applied to existing materials in print or applied as a sticker on top.

**Comment by sabrinang** [comment]
@xmatthewx @edrushka @Saallen Can I get your feedback? Redpen here: https://redpen.io/ea7e62fa798fedad44

I adapted a single cube to make it look like an abstract house, I think the gear outline visually ties it back to mozfest a bit more than the circle
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/2492510/30441906-a9505d56-992f-11e7-9fec-e5555401036c.png">

**Comment by xmatthewx** [comment]
See my comment here: https://github.com/MozillaFoundation/mozfest-design-2017/issues/21#issuecomment-329575552. 

The icon looks great. But given the nature of this event series, and limitations with the venue, I'm concerned that people less familiar with MozFest won't have the chance to build an awareness of MozFest. I think we should stick with the gear icon in the mozfest lockup, and skip a specific icon for House.

**Comment by sabrinang** [comment]
Progress and feedback has been collected on redpen and we agree that a vertical stacked lockup would work in various applications:
![brand - lockup logo wordmark](https://user-images.githubusercontent.com/2492510/30838472-8bb7b0ba-a220-11e7-98ad-c3f42b77e92a.jpg)

all SVG PNG and working files can be found in gdrive: https://drive.google.com/open?id=0B4Q8pzCpDS_eWkR5Z1Q2T2ZrWG8

**Comment by sabrinang** [comment]
## Post MozFest House Documentation

The mozfest house brand had a versatile lockup where the logo could be used outside of the box and separate from the workmark. The main palette was warm pink orange tones that contrasted the stark white/black while using the wavy textures to tie in the space together:


It was seen used in small and large scale applications
![mozfest-house-15](https://user-images.githubusercontent.com/2492510/32972785-f444ee2a-cba8-11e7-8fb5-5e6acacd15c9.jpg)

As a lockup, it was seen applied vertically and horizontally in black or white:
![mozfest-house-27](https://user-images.githubusercontent.com/2492510/32972753-c48d7da0-cba8-11e7-9b76-5cbf8adeee74.jpg)

The highlights could be removed and paired with just the logo in some applications:
![mozfest-house-21](https://user-images.githubusercontent.com/2492510/32972783-ef6c03d4-cba8-11e7-9589-f594a37fa99a.jpg)
 
Branding on the podium
![house pdium](https://user-images.githubusercontent.com/2492510/33190689-589e603a-d064-11e7-9ccb-a8ebe9a00dd9.jpg)
![mozfest-house_podium](https://user-images.githubusercontent.com/2492510/33190733-fd7dd374-d064-11e7-90ca-842505f0da6c.jpeg)
![img_3034](https://user-images.githubusercontent.com/4515662/33191229-ee35c4b0-d06b-11e7-911f-d892b7592086.JPG)

![mozfest-house-3](https://user-images.githubusercontent.com/2492510/32972800-108ae04e-cba9-11e7-93a6-34e7b5f5b2b3.jpg)

**Comment by xmatthewx** [comment]
this is great. @sabrinang - as you collect these images, can you drop them in a folder on drive (if you aren't already) ... for easy use elsewhere. Send a link my way. Thanks!!

**Comment by sabrinang** [comment]
@xmatthewx Yes, images are uploaded on gdrive and links can be found on this photo issue: https://github.com/mozilla/mozillafestival.org/issues/727#issuecomment-345358662
