### ISSUE TITLE
Swag: Water Bottle

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2017#53]
We're planning to get a similar water bottle we had in 2014. 

The vendor is [WeBrandIt](https://www.webrandit.co.uk/W12109).

They come in set colours and the options are below:
![waterbottlecolours](https://user-images.githubusercontent.com/30226684/30751492-61bc03f4-9fb1-11e7-98f8-6466ed025072.png)

We have quoted for a print area as shown in the images above that has a print area of 97 x 90mm in a single colour.

**Comment by sabrinang** [comment]
Black or purple looks nice and we can use the white gear in the print area
redpen here for feedback: https://redpen.io/gtecd53af55c047d47
<img width="1118" alt="mockup" src="https://user-images.githubusercontent.com/2492510/30825412-be170d28-a1e7-11e7-92c6-49c67ca21cc9.png">


White gear logo svg: https://drive.google.com/open?id=0B4Q8pzCpDS_eY2xtLVFEVk1ycDA

**Comment by edrushka** [comment]
@marcwalsh can we have multiple colours??! 😁

**Comment by marcwalsh** [comment]
@edrushka @sabrinang - We can indeed - for the same price as well...

💃

**Comment by marcwalsh** [comment]
**PROOFS ATTACHED BELOW**

Let me know if we're good to go to print with these? 💃 

![mozilla foundation - metallic roll up water bottle w12109 - webrandit - artwork approval black](https://user-images.githubusercontent.com/30226684/30936173-eb6402d8-a3ca-11e7-8f78-edfc31f0e4a3.png)

![mozilla foundation - metallic roll up water bottle w12109 - webrandit - artwork approval purple](https://user-images.githubusercontent.com/30226684/30936179-ee28a01e-a3ca-11e7-97a4-fcdaf1eb070c.png)

**Comment by edrushka** [comment]
@marcwalsh how many colours are we ordering? Just 2? If so, @sabrinang do we want to do black? People will be able to write their names w/ Sharpie on the other colours. If we can have a rainbow, it will be less necessary to write names on bottles.

**Comment by sabrinang** [comment]
I think the webrandit waterbottle includes a frosted white strip (area to write your name) so black won't be an issue? I asked the designers in the office for some feedback and it would be great if we can get black, purple, cyan and yellow.
![waterbottle-mockups](https://user-images.githubusercontent.com/2492510/30939366-0a8e8450-a392-11e7-8f28-df50de3a9754.jpg)

Would this work? @edrushka @marcwalsh

**Comment by edrushka** [comment]
works for me if Marc says yes to four colours! Thanks, Sabrina!

**Comment by marcwalsh** [comment]
Great! They said previously we can have a mix as the artwork is the same. So will request these. @sabrinang are you happy with the proof above? If so I'll get them ordered!

**Comment by sabrinang** [comment]
Proofs above are good to go! Please double check that the white strip comes with these water bottles (specifically for the black one)

**Comment by marcwalsh** [comment]
Sent to printers! We're getting all 4 colours! 🌈

**Comment by sabrinang** [comment]
## Post MozFest Documentation

These came in the 4 colours in a transparent plastic with a white strip on the back. I tried to find a black bottle on Sunday but they seemed to run out first out of the colours.
![mozilla-festival-2017-171](https://user-images.githubusercontent.com/2492510/33045590-3ea63e96-ce02-11e7-9ae2-c24497d9f9f3.jpg)
![20171027-mozfest-signage-12](https://user-images.githubusercontent.com/2492510/33045766-d04b9030-ce02-11e7-8d71-4090c3b3f081.jpg)

These come with a carabiner so you can clip them anywhere! Esme is modeling the bottle in the midst of hula hooping ✨
![20171027-mozfest-90](https://user-images.githubusercontent.com/2492510/33046620-9a5244b6-ce06-11e7-99b0-714c68a5959b.jpg)
