### ISSUE TITLE
MozFest House: Cups

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#54]
### Description:
We will have 5000 branded cups at MozFest house since the space can't have branding on walls the cups are an opportunity to have it showcased.

### Related Issue:
blocked by https://github.com/MozillaFoundation/mozfest-design-2017/issues/52
__________________________
#### Print Deadline
September 29

**Comment by sabrinang** [comment]
@marcwalsh Can you supply vendor details and if they have a template/dimensions to follow? (unsure if the cup itself is branded or a removable sleeve)

**Comment by edrushka** [comment]
@marcwalsh we've settled on MozFest House logo so need dimensions to complete this.

**Comment by marcwalsh** [comment]
@sabrinang  - Sorry for the delay this is the artwork for the cups. 
[8oz DW Paper Cup Template Xpress Run.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1338606/8oz.DW.Paper.Cup.Template.Xpress.Run.pdf)

**Comment by sabrinang** [comment]
![coffee cup preview](https://user-images.githubusercontent.com/2492510/31034357-929db79e-a518-11e7-9dee-5c840fa40109.jpg)
<img width="1003" alt="coffee cup preview" src="https://user-images.githubusercontent.com/2492510/31034338-8285e6ec-a518-11e7-90ee-cafec4564fa4.png">



.pdf is here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eM2htMmZVR3BTN1E/view?usp=sharing
.ai file is available here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eTnpDVHRoZnJLXzQ/view?usp=sharing

older redpen iterations here: https://redpen.io/p/coda79d099fb9566a4

@marcwalsh Can you review this file if it is okay to send to print? Since we have the print deadline today

**Comment by sabrinang** [comment]
@edrushka mentioned this has been sent to print - closing!

**Comment by sabrinang** [comment]
## Post MozFest House Documentation

Branded insulated cups were used by baristas to serve beverages and they added a splash of colour to the space.
![mozfest-house-17](https://user-images.githubusercontent.com/2492510/32521909-1cc0ed9a-c3ca-11e7-9c1a-0ebc1bf77171.jpg)
![mozfest-house-13](https://user-images.githubusercontent.com/2492510/32521916-2263f2e2-c3ca-11e7-8dc5-55d9e83c8892.jpg)
![mozfest-house-12](https://user-images.githubusercontent.com/2492510/32521927-28b494e4-c3ca-11e7-9605-e9a33cf51144.jpg)
![mozfest-house-5](https://user-images.githubusercontent.com/2492510/32521940-359f3b6e-c3ca-11e7-843e-a994c3c8de8a.jpg)
![image uploaded from ios 4](https://user-images.githubusercontent.com/4515662/33191189-592d02b6-d06b-11e7-95d3-7f4e3c2eae42.jpg)
Someone got creative with it to use it as decor or made a string telephone in the MozFest space!
![20171027-mozfest-156](https://user-images.githubusercontent.com/2492510/32969288-5b644656-cb99-11e7-83c2-a23e5e38ab6a.jpg)
