### ISSUE TITLE
Social Profile Cards For Each Speaker in Speaker Series

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/mozfest-design-2017#55]
Create profile cards for each speaker (16 in total) to be included in a package sent to them asking them to promote their talk. Will make using 1200px by 628px template.

**Comment by beccaklam** [comment]
Redpen for this here: https://redpen.io/p/afd81c048a44b1f919 CC: @tlasadea

**Comment by beccaklam** [comment]
Finished 16 designs: https://redpen.io/p/afd81c048a44b1f919 @tlasadea

**Comment by tlasadea** [comment]
These are approved @beccaklam
