### ISSUE TITLE
Social templates for quotes/text in same colours scheme as 6 spaces

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/mozfest-design-2017#56]
Create templates for quotes/text that are colour coded according to the MozFest spaces.
Link to Mozfest space colours and icons: https://docs.google.com/a/mozilla.com/presentation/d/1aGORKRRTzvVXo19XeBYeOZbDA5QkM-X1vCjNMpcj9Vc/edit?usp=sharing

**Comment by beccaklam** [comment]
Quote Templates: https://redpen.io/p/uxb50bbefd6b571957 @tlasadea

**Comment by edrushka** [comment]
@beccaklam are these available anywhere? We could use these (without text) for the feedback surveys. Need 3 different colours for the 3 different surveys.

**Comment by beccaklam** [comment]
Hi @edrushka here's the psd template: https://drive.google.com/open?id=0BzuBOR2VJQqUdEdDQUw3RzN4TEU

**Comment by edrushka** [comment]
## Post MozFest Documentation

These were well used and looked fabulous. Garnered lots of retweets. A really great asset.
<img width="622" alt="screenshot 2017-11-24 13 33 55" src="https://user-images.githubusercontent.com/4515662/33224262-5f1973d8-d11c-11e7-80c9-66da3c127cd9.png">
