### ISSUE TITLE
Social Gifs + graphic for announcing the live speaker series

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/mozfest-design-2017#57]
Create gifs and a social graphic to announce the live speaker series.

**Comment by beccaklam** [comment]
@tlasadea @natalieworth https://redpen.io/rd0391487040ea6a62 <-- Work In Progress, but feedback welcome. I need to fix the timing and the animation curves, but any other thoughts?

**Comment by natalieworth** [comment]
@beccaklam really awesome! maybe the 'mozfest speaker series' part could be a bit larger as it'll probably appear small on social. I'd bump the saturation/ contrast up a little too so the colours are more punchy.

**Comment by tlasadea** [comment]
@beccaklam commented on Redpen, but you smashed it. Love.

Agree with @natalieworth on increasing text size.

**Comment by tlasadea** [comment]
@HPaulJohnson please feedback: https://redpen.io/rd0391487040ea6a62

**Comment by edrushka** [comment]
## Post MozFest Documentation

This was tweeted. Looked great!

<img width="707" alt="screenshot 2017-11-24 13 25 31" src="https://user-images.githubusercontent.com/4515662/33224173-6b3c3430-d11b-11e7-86b0-183ddaa17a20.png">
