### ISSUE TITLE
Social Gifs + graphic for announcing friday night festival

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/mozfest-design-2017#58]
Create gifs and a graphic for announcing the Friday night festival.

**Comment by beccaklam** [comment]
@tlasadea https://redpen.io/gr846385e57c7c9e1f

**Comment by beccaklam** [comment]
@tlasadea updated party time gif: https://redpen.io/jg51cb652cebf04797

**Comment by edrushka** [comment]
Don't think this one got tweeted. A shame - it's so fun!
