### ISSUE TITLE
Opaque Banner/border for Pictures

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/mozfest-design-2017#59]
Create an opaque banner/border for pictures shared on social.

**Comment by beccaklam** [comment]
@tlasadea https://redpen.io/p/mudc43cb433441b2b1 would this work? @sabrinang can we use the logo this way, with a gradient applied on top?

**Comment by sabrinang** [comment]
@beccaklam I would avoid using gradients on the logo since it includes mozilla in it I have been following these variants: 
<img width="776" alt="image" src="https://user-images.githubusercontent.com/2492510/31246512-7d498f18-a9c2-11e7-9e5c-bbdd8220250a.png">

**Comment by beccaklam** [comment]
@sabrinang thanks for the flag! I'll make changes :)

**Comment by beccaklam** [comment]
@tlasadea @sabrinang Updated to black and white logo here: https://redpen.io/p/mudc43cb433441b2b1 It's not that exciting ... but clean and to the point?

**Comment by tlasadea** [comment]
@HPaulJohnson please feedback on this redpen: https://redpen.io/p/mudc43cb433441b2b1
