### ISSUE TITLE
Snippet Icons For Moz Fest

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/mozfest-design-2017#60]
Create a snippet to promote MozFest.

**Comment by beccaklam** [comment]
@tlasadea @sabrinang https://redpen.io/p/yr1b78b9067965475b

**Comment by tlasadea** [comment]
@HPaulJohnson please feedback: https://redpen.io/p/yr1b78b9067965475b

**Comment by edrushka** [comment]
@Saallen cute animated cog here: https://redpen.io/faee58d7d8970eb0d9
