### ISSUE TITLE
Cut down promotional video to one minute

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/mozfest-design-2017#61]
Cut down this [video](https://vimeo.com/205552025/37560e3619) can be cut down to the 1 minute mark.

**Comment by beccaklam** [comment]
@tlasadea will this work? https://drive.google.com/open?id=0BzuBOR2VJQqUamdCaXdFcVp2TE0

**Comment by sabrinang** [comment]
## Post MozFest Documentation
<img width="639" alt="image" src="https://user-images.githubusercontent.com/2492510/33221912-12e050ea-d108-11e7-871a-009b4e08d0f4.png">
