### ISSUE TITLE
Email headers for each of the 6 spaces

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/mozfest-design-2017#62]
Create Email headers for each of the 6 MozFest spaces.

**Comment by sabrinang** [comment]
@edrushka Do you know what we use to send out our Festival emails and what dimensions these email headers should be?

**Comment by edrushka** [comment]
We send out festival emails using ti.to - I can get the exact information about banner size.
@beccaklam can you clarify:
- by header, do you mean banner image?
- what the headers will be used for? We won't be sending any space-specific emails.

**Comment by beccaklam** [comment]
@tlasadea ^ do you know what the email headers will be used for? Re: #9 in this brief: https://docs.google.com/a/mozilla.com/document/d/1iU1KLFgWHFBWWZCzd3KIU5cr09PCtD80kHgDhJ23goM/edit?usp=sharing

**Comment by edrushka** [comment]
Oh, if these came from the advocacy mini-brief then the Ti.To information doesn't apply - we only use it to send festival emails. Not sure what platform is used to send advocacy emails.

**Comment by tlasadea** [comment]
Hey @beccaklam these were for e-mails that would be going out post moz-Fest
& used in the Medium blog.

**Comment by beccaklam** [comment]
@tlasadea Not sure what exactly you were looking for so let me know if you need any changes: https://redpen.io/p/hbfa5ea5df1c42d9ac

**Comment by tlasadea** [comment]
Hey @edrushka just to clarify - all the content @beccaklam is designing for social is for the entire festival promo, not just advocacy specific. The email headers are banners as you mentioned above - but if there won't be any space-specific emails these can be used for any blog content that is published post-Mozfest. Thanks @beccaklam, these look ace, have left feedback on Redpen.

**Comment by edrushka** [comment]
## Post MozFest Documentation

These were modified for use in the attendee, facilitator and staff surveys:
<img width="1247" alt="screenshot 2017-11-24 10 55 40" src="https://user-images.githubusercontent.com/4515662/33221686-34be5a24-d106-11e7-9915-7a5117223e05.png">

**Comment by edrushka** [comment]
These might have been good for the app as graphics for each space.

**Comment by sabrinang** [comment]
These graphics were posted on mozillafestival twitter on Oct 23
<img width="425" alt="image" src="https://user-images.githubusercontent.com/2492510/33221845-a3f466b2-d107-11e7-8d73-793ef6e71df8.png">
