### ISSUE TITLE
Create a sign for Pulse kiosk

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mozfest-design-2017#63]
Like last year, we'd like to have a kiosk for Pulse, so attendees can join, add their projects. This year, we should also have profiles for people. 

Quantity: 2

@marcwalsh - the sign last year worked fine, though it was tricky to mount. Can you think of way to do it with a stand or easel?

@kristinashu and @sabrinang - can you tag team on this?

**Comment by marcwalsh** [comment]
@xmatthewx here's a couple of options for you:

[Floor Standing](https://www.pixartprinting.co.uk/displays/point-of-sale-displays/floor-display/)

[Free Standing](https://www.pixartprinting.co.uk/displays/point-of-sale-displays/dover/)

**Comment by xmatthewx** [comment]
Interesting. Thanks @marcwalsh. What do you think @kristinashu? Low to the ground, but maybe we could pair it with a smaller simple horizontal sign mounted to the top of the monitor.

**Comment by marcwalsh** [comment]
@xmatthewx @kristinashu - Just so you're aware the print deadline for the stands would be around the 10th October.

**Comment by kristinashu** [comment]
@sabrinang @xmatthewx will something like this work? It's the smaller floor stand option. 

<img width="519" alt="screen shot 2017-10-10 at 3 03 13 pm" src="https://user-images.githubusercontent.com/1068783/31413033-5ddd102e-adcc-11e7-86d1-aad52c5bb46f.png">


<img width="323" alt="screen shot 2017-10-10 at 10 19 46 am" src="https://user-images.githubusercontent.com/1068783/31400459-8fbcb360-ada4-11e7-844c-74b610d61790.png">

If we've missed the deadline then can we just print on paper at Ravensborne?

**Comment by kristinashu** [comment]
The floor stand actually seems large. @sabrinang @marcwalsh are we able to print this on two A2 cardboard pieces and then tape them together to make an A frame? I think we did this a bit last year.

**Comment by xmatthewx** [comment]
@marcwalsh - can we order 4 dowel rods? maybe 1cm x 1m or similar? i think this will help with mounting this sign above kiosk throughout weekend. 

we can do two A2 on cardboard as an A frame as kristina's suggests during sci fair and demos.

**Comment by kristinashu** [comment]
Here is the print pdf: [PulseMozFestSign-A2.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1376879/PulseMozFestSign-A2.pdf)

(cta has been removed)
<img width="518" alt="screen shot 2017-10-11 at 12 14 56 pm" src="https://user-images.githubusercontent.com/1068783/31461256-db367c98-ae7d-11e7-8c2b-c1e78359e43a.png">

**Comment by marcwalsh** [comment]
Sent to printers! 💃 - ETA: 20th October

**Comment by kristinashu** [comment]
Amazing! Thank you!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The sign was seen at the Science Fair and at the kiosk throughout the Festival beside a monitor screen for demo.
![mozilla-festival-2017-80](https://user-images.githubusercontent.com/2492510/33044974-f48ca2b6-cdff-11e7-896c-fc649b568b36.jpg)
![20171027-mozfest-signage-20](https://user-images.githubusercontent.com/2492510/33045110-9093318e-ce00-11e7-9b8b-a4040e6bf000.jpg)
We should probably consider a research poster as well. Tais wrote one during MozFest to attract people to collect feedback and if we coordinated earlier we could of printed that sign instead.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/2492510/33045235-0389abd2-ce01-11e7-8564-8e2142b4ee42.png">
