### ISSUE TITLE
MozFest House: Table Cloths

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#64]
### Description:
These table cloths might just be a solid colour (black?) if not they will have the house lockup or generic mozilla logo so they are reusable for future events.

__________________________
#### Print Deadline
October 4

**Comment by sabrinang** [comment]
@marcwalsh Does the table cloth have a template? I assumed we are just putting the logo or lockup on black so mocked up the two options:
![mozilla-festival-house-2017_table-cloth](https://user-images.githubusercontent.com/2492510/31368288-af451100-ad31-11e7-9156-7494075fb412.jpg)

white mozilla only logo files here: https://mozilla.ninja/s/Mozilla_Large-Logo_One-color-white.zip
white mozilla festival house lockup here: https://drive.google.com/file/d/0B4Q8pzCpDS_eOVRwNS1QVmJyaDA/view?usp=sharing

**Comment by edrushka** [comment]
I suggest the House lockup w/black background

**Comment by marcwalsh** [comment]
Printed: ETA - 20th October

**Comment by sabrinang** [comment]
## Post MozFest House Documentation

Black table cloths were used by the barista and in the registration area. It helped refine the space and contrasted nicely in the white space. It accented the lockups/gradients well and was practical to keep things looking clean.
![mozfest-house-4](https://user-images.githubusercontent.com/2492510/32521551-b7b44e70-c3c8-11e7-9043-1ac220dd4c9d.jpg)
![mozfest-house-6](https://user-images.githubusercontent.com/2492510/32521561-be7837a8-c3c8-11e7-9e78-c88dcc5c73f7.jpg)
![mozfest-house-15](https://user-images.githubusercontent.com/2492510/32521570-c800c970-c3c8-11e7-9218-bf17f9f46b2a.jpg)
![mozfest-house-39](https://user-images.githubusercontent.com/2492510/32521579-d16cdb70-c3c8-11e7-96ef-434cb927875c.jpg)
