### ISSUE TITLE
MozFest House: Generic A4 Poster Signage

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#65]
### Description:
Make a pattern/textured pattern that can be thrown in Word and remixed to make letter size posters. This is a generic template to be remixed by Lucie and Marc.
__________________________
#### Print Deadline
These may be done on site

**Comment by sabrinang** [comment]
@marcwalsh For these signage templates, instead of using Word, I think using Google Slides would be more accessible to make your own signs. Template here: https://docs.google.com/presentation/d/14IT387tx_AlvaXy7Ex28p2GRlBkx_qMmtKcnANGaLpg/edit?usp=sharing

Just go to _**File > Make a copy...**_ to create your own set of signs and please use Zilla Slab seen on the placeholder text then you can _**File > Print**_ from there.

@edrushka Can you review the template designs?

**Comment by marcwalsh** [comment]
@sabrinang - Slides works perfectly!

We also need a portrait version of these, please. 

In terms of design, can the borders be made thicker? I've attached a photo from Lucie that shows the type of frame they are being put into and the borders might be lost. You might lose up to an inch around the page judging by the image.

![00fdf177-149e-4d2f-923b-dcf99ab58d43_720](https://user-images.githubusercontent.com/30226684/31387214-8b74deb4-adc1-11e7-8c18-87c4d610f029.jpg)

**Comment by edrushka** [comment]
R+ on horizontal version of template.

**Comment by sabrinang** [comment]
Vertical sign templates are available here: https://docs.google.com/a/mozilla.com/presentation/d/10EvyxVRryx9i1VPNIaexpy_49SwuOAHx4_h6KcA0Xt8/edit?usp=sharing

<img width="953" alt="image" src="https://user-images.githubusercontent.com/2492510/31746233-25f57e94-b41b-11e7-8090-0201c5d1710e.png">

**Comment by marcwalsh** [comment]
Closing as we're using them onsite and working perfectly! 👍

**Comment by sabrinang** [comment]
## Post MozFest House

These hackable signs were seen throughout the RSA space and helped distinguish the many rooms inside. There were bus stop sign holders and wall mounted holders. Bus stop frames overlapped signs by 1cm or so (use thicker border template) and wall mounted frames did not overlap. The slide file included a variety of border styles but next time archive the rest so only the thick border design is hackable.

![mozfest-house-34](https://user-images.githubusercontent.com/2492510/32518511-ab704772-c3be-11e7-99a9-ab860bd56df6.jpg)
![mozfest-house-36](https://user-images.githubusercontent.com/2492510/32518529-b2823c3c-c3be-11e7-8998-b82c821ed131.jpg)
![mozfest-house-35](https://user-images.githubusercontent.com/2492510/32518521-ae4934e0-c3be-11e7-952c-1d9e0cf29671.jpg)
![mozfest-house-37](https://user-images.githubusercontent.com/2492510/32518532-b46f5ea8-c3be-11e7-8527-522deb0dfbdf.jpg)
