### ISSUE TITLE
MozFest House: Branded Pillar Totems

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#66]
### Description:
Incorporate colour and house lockup to bring in some branding in to the space.

(size approximately 45” in diameter but the base which is square is 19”x19”) 

### Format
https://www.pixartprinting.co.uk/displays/point-of-sale-displays/totem-3-xl/
__________________________
#### Print Deadline
October 3

**Comment by marcwalsh** [comment]
After talking to Lucie and Sarah yesterday we now required:

- 2x [Totem 3 XL](https://www.pixartprinting.co.uk/displays/point-of-sale-displays/totem-3-xl/)
- 8x [Totem 3](https://www.pixartprinting.co.uk/displays/point-of-sale-displays/totem-3)

This will the same design - Sarah and Lucie mentioned it would be good to have the same background as the cups. As they are looking at something similar for lighting pillars.

**Comment by sabrinang** [comment]
@edrushka Can you give me some design feedback on lockup placement on these totem designs? (one is regular size and the other is XL) https://redpen.io/p/fu55d9c7167e519040
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/2492510/31191984-c0fa892a-a8f4-11e7-8b0c-c3f9f134ecb8.png">

**Comment by edrushka** [comment]
I commented in the redpen 🐍

**Comment by edrushka** [comment]
hi @sabrinang I shared with Sarah and here is more feedback:
Please use the larger vertical lockup. It can either be repeated 3x on all sides, or at minimum on the center panel.  

I assume flipping the entire lockup on its side to make it extra big is not possible.

**Comment by sabrinang** [comment]
@edrushka I tried flipping it previously on the side but did not include since it makes reading it strange on a large totem so I don't like it - see comparison example:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/2492510/31201287-0c6a7fb4-a913-11e7-98df-a0da7e21036a.png">

Thanks for the feedback, I updated the redpen with the skinnier totem with all vertical lockups and XL totem with both but made lockups larger: https://redpen.io/p/fu55d9c7167e519040 

I will export these final files shortly.

**Comment by edrushka** [comment]
Oh jeez, yah, the flipped version looks super weird 😖

**Comment by sabrinang** [comment]
@marcwalsh Both Totem 3 and Totem 3 XL files (.pdf and .ai) can be found here on google drive and ready to print: https://drive.google.com/open?id=0B4Q8pzCpDS_ecmFEM3dyZjlqdFE
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/2492510/31202557-f2118f4a-a917-11e7-8a96-b90d85cda12d.png">

**Comment by marcwalsh** [comment]
Sent to Print! :D ETA - 16th October

**Comment by sabrinang** [comment]
## Post MozFest House Documentation
Totems were found by the entrance doorways and Totems XL were behind registration area. These provided great surface area for branding.
![mozfest-house-8](https://user-images.githubusercontent.com/2492510/32509456-332ab7d2-c3a2-11e7-9e96-fd15d27dae21.jpg)
![mozfest-house-32](https://user-images.githubusercontent.com/2492510/32509482-48472240-c3a2-11e7-981e-bcfe9792e723.jpg)
![mozfest-house-39](https://user-images.githubusercontent.com/2492510/32509491-4f55c74e-c3a2-11e7-8385-d2a044bb99fb.jpg)

Great for selfies too! 👍 
<img width="497" alt="image" src="https://user-images.githubusercontent.com/2492510/32969115-a7269fb8-cb98-11e7-9482-c064c4e15b62.png">

**Comment by edrushka** [comment]
Note re: totems - these are too big for the Mozilla office elevator and need to be carried by hand up the stairs (very heavy!) Try to get these delivered directly to the venue.
