### ISSUE TITLE
MozFest House: Wristbands

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#68]
### Description:
Choose a colour. The rest can just be the house lockup or typed out with Zilla Slab.

### Supplier
https://www.aawristbands.co.uk/?gclid=CM-E94WWk9YCFU-17QodWvYGUw
__________________________
#### Print Deadline
October 12

**Comment by sabrinang** [comment]
![mozilla-festival-house-2017_wristbands](https://user-images.githubusercontent.com/2492510/31366795-e4456120-ad27-11e7-9212-16339ed7f61b.jpg)
I highlighted 7 colours and the settings for the wristbands (1", Logo Left of Text and if there is two lines of text to use Arial Black medium and Arial small). If there is just one line of text then just Arial Black works.

Here is the Mozilla Festival House lockup .svg file: https://drive.google.com/file/d/0B4Q8pzCpDS_eb3pJWTRFc1JoYWs/view?usp=sharing

**Comment by sabrinang** [comment]
@edrushka Can you review if these design settings are appropriate for whatever text content is including on these bands?

**Comment by edrushka** [comment]
Design looks good so far. @Saallen @lucieclick do you want to print individual event names on the actual bands? IMO this isn't necessary, and we can simply assign each event a unique colour.

**Comment by Saallen** [comment]
For major events we do like
View source
MisInfoCon
Open News

the rest will be signified with colours- 
cc @lucieclick

**Comment by edrushka** [comment]
@sabrinang can you please mock up 4 bands
- 1 plain (house lockup only)
- 1 (different colour) with lockup and **MisinfoCon** (one line only, don't need the second additional line of text)
- 1 (different colour) with lockup and **View Source** (one line only, don't need the second additional line of text)
- 1 (different colour) with lockup and **OpenNews Unconference on Journalism Tech** (can split onto 2 lines but keep equal weight on both lines.

Thank you! 🌻

**Comment by Saallen** [comment]
For major events we do like
View source
MisInfoCon
Open News

the rest will be signified with colours- 
cc @lucieclick

**Comment by lucieclick** [comment]
Hi - yes for the larger events, and some of the others like Netgain I'd previously asked them what they'd like on their wristbands so if possible I'd like to do this?
They are all on here  https://docs.google.com/spreadsheets/d/1_FEF2gn-6YMl0YwV4wMCrXs--GcDidug7YXCqxPwOXU/edit#gid=295064791- those that say "MozFest" are the ones that can be the generic. Is that OK @Saallen @edrushka ?

**Comment by edrushka** [comment]
@lucieclick can you open permissions on that doc please.

**Comment by edrushka** [comment]
@sabrinang It looks like we need 8 custom bands:

1. BBC Adaptive Narratives	(band colour: blue)
2. MisInfocon	(band colour: yellow)
3. View Source	 (band colour: blue)
4. Netgain (band colour: unspecified)
5. @moztechspeakers	 (band colour: unspecified)
6. Open News	 (band colour: unspecified)
7. Databox HackDay		 (band colour: unspecified)
8. Cities of Learning	 (band colour: unspecified)

**Comment by sabrinang** [comment]
![mozilla-festival-house-2017_wristbands-colours](https://user-images.githubusercontent.com/2492510/31560082-d4246bc8-b007-11e7-9c68-61a3ec516ce4.jpg)


- Using Arial Black the text is entered on the Wristband Customiser on aawristbands.co.uk (no custom font option)
- The only design file needed from me is the Mozilla Festival House lockup .svg file here: https://drive.google.com/file/d/0B4Q8pzCpDS_eb3pJWTRFc1JoYWs/view?usp=sharing
- 1", Logo Left of Text, large Arial Black

@edrushka Content/colour review?

**Comment by edrushka** [comment]
R+ from me on colours. Can you make one last all purpose band that simply says MozFest House? Should be different colour from the rest.

**Comment by sabrinang** [comment]
Ah I didn't see this all-purpose one earlier. Let's go with black and use an alternative lockup so it stands out against the black wristband - I exported it together as a .svg here: https://drive.google.com/open?id=0B4Q8pzCpDS_eSmluS2lQaERaV1E
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/2492510/31565972-a3a9367a-b01d-11e7-92a7-ecbdea78531a.png">

**Comment by Saallen** [comment]
Hey @sabrinang 
If there are two events using the all purpose bands we want them in different colours so that the event leads can distinguish their audience. Could you make one more all-purpose in a different colour please? Thanks


cc @marcwalsh @lucieclick

**Comment by sabrinang** [comment]
Yes, let's add Gold to the order as an additional all-purpose band.
<img width="768" alt="image" src="https://user-images.githubusercontent.com/2492510/31579156-e8c1e74e-b0e4-11e7-85f1-25b46013d3d0.png">

**Comment by lucieclick** [comment]
@sabrinang Wristbands all look great for Mozfest House!

**Comment by lucieclick** [comment]
Hi @sabrinang  - not sure if its too late, but I just noticed Netgain on the wristbands should be spelt "NetGain" - with the capital G in the middle.

**Comment by sabrinang** [comment]
@lucieclick The names are entered in the wristband customizer interface so if they are not ordered yet it is not too late.

@marcwalsh  Here are the **correct names to be entered:**
- BBC Adaptive Narratives
- MisInfocon
- View Source
- NetGain
- @moztechspeakers
- Open News
- Databox HackDay
- Cities of Learning

![mozilla-festival-house-2017_wristbands-colours](https://user-images.githubusercontent.com/2492510/31627353-df091e38-b261-11e7-8e9d-566ae1aeeb12.jpg)

**Comment by marcwalsh** [comment]
Sent to print! ETA: Friday

**Comment by sabrinang** [comment]
## Post MozFest House Documentation

The wristbands were used throughout the festival house week to differentiate participants for various events. Instead of black and gold, silver and gold was printed with black text above (no white text version used):
![mozfest-house-21](https://user-images.githubusercontent.com/2492510/32469111-0e3e8de6-c306-11e7-9282-08f96e91bd2a.jpg)
![mozfest-house-22](https://user-images.githubusercontent.com/2492510/32469113-1059610a-c306-11e7-84d1-740d9ea07bcb.jpg)

Colours were easy to spot from a distance such as these yellow wristbands at MisInfocon:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/2492510/32469737-edb46854-c308-11e7-8a68-c7120c65643e.png">
