### ISSUE TITLE
Registration Table: Understand Me Better Cards

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#70]
At the Youth & Press & Accessibility registration table, there will be "Understand Me Better" cards the size of business cards for people to use to hand out when communication is difficult

**Comment by edrushka** [comment]
@marcwalsh is figuring out where to print these since we don't need many. Likely we'll design something very simple and use the extras next year.

**Comment by edrushka** [comment]
Side A: Understand me better
Side B: 
I am _________________
You can help me by ____________________

These should be very simply designed (w/plan to reuse for next year)

we'll have a hole punch available where we pass out these cards for people to optionally attach to their lanyards

**Comment by marcwalsh** [comment]
@sabrinang - Link to the product is [here](https://www.pixartprinting.co.uk/business-cards/eco-friendly-business-cards/) - This requires roughly a 10-day turnaround.

Sizing is up to you. I'd say the 9cm x 5cm is quite nice.

Price wise it makes sense to go for the 250 print run and reuse, as we'd be paying a similar price for a smaller quantity.

**Comment by edrushka** [comment]
Based on the [Dyslexia association guidelines](http://www.bdadyslexia.org.uk/common/ckeditor/filemanager/userfiles/About_Us/policies/Dyslexia_Style_Guide.pdf), I suggest 12-14pt plain font (they actually recommend Comic Sans - I DARE YOU, SABRINA 😆) with a small MozFest lockup on the front (without the year, so we can reuse).

**Comment by sabrinang** [comment]
@edrushka Please review content/design on redpen: https://redpen.io/p/rjb2abd04833b85efb

Print .pdf is here: https://drive.google.com/open?id=0B4Q8pzCpDS_eYXBlaTFia2NKanc

**Comment by edrushka** [comment]
R+ Thank you! 🌷

**Comment by sabrinang** [comment]
@marcwalsh Ready for print 
Print .pdf is here: https://drive.google.com/open?id=0B4Q8pzCpDS_eYXBlaTFia2NKanc

**Comment by marcwalsh** [comment]
Sent to Print!

**Comment by sabrinang** [comment]
## Post MozFest Documentation
These were found at the Youth Press Accessibility table near registration.
![mozilla-festival-2017-202](https://user-images.githubusercontent.com/2492510/33044725-dd43fb46-cdfe-11e7-8e28-db3183f0a312.jpg)
![mozilla-festival-2017-194](https://user-images.githubusercontent.com/2492510/33044727-e04a68b6-cdfe-11e7-9500-3d787a20267e.jpg)
![mozilla-festival-2017-165](https://user-images.githubusercontent.com/2492510/33044764-04807f0e-cdff-11e7-97c7-a24e81fc3818.jpg)
![mozilla-festival-2017-166](https://user-images.githubusercontent.com/2492510/33044765-049def9e-cdff-11e7-93ef-04194089d7ce.jpg)
