### ISSUE TITLE
Design Festival Guide Cover

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/mozfest-design-2017#71]
Making a separate bug for this as it has to be completed first (I think!).
Repen progress so far is here: https://redpen.io/cs1cf056abdd34abab

R? @sabrinang @edrushka Can you guys please review this and loop in others as needed?

Looking specifically at the front cover, the back cover (participation guidelines), the pocket and the accompanying message, as well as how the map slots into the pocket.

![mozfest2017-cover-v3-sm-09-09](https://user-images.githubusercontent.com/1186326/31108229-dfaaaf10-a7c5-11e7-89fa-27d6c593a382.jpg)

**Comment by cassiemc** [comment]
The printer said they don't do braille, but I wondered if braille stickers were a thing, and, they are! https://www.pia.co.uk/en/services/braille-labels @marcwalsh This would be pretty sweet, what do you think?

**Comment by edrushka** [comment]
Although I love the braille stickers, we don't have the capacity to stick 2500 onto booklets. I think we'll have to pass if the printer can't incorporate on the last page 😞 

Next year, if we have a pocket, let's look at inserting a braille postcard w/ lots of information.

**Comment by edrushka** [comment]
@marcwalsh also confirming that these maps are printed separately from the Festival Guide, and will not be inserted, but rather will be available on the swag table for people to take as they please.

**Comment by marcwalsh** [comment]
@edrushka - These will be printed separately and available on the Swag / Rego tables.

**Comment by cassiemc** [comment]
@edrushka @sabrinang Needs final review: https://redpen.io/cs1cf056abdd34abab
