### ISSUE TITLE
MozFest Summary Creative for Social 

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/mozfest-design-2017#72]
Create a summary graphic for MozFest

**Comment by tlasadea** [comment]
#8

**Comment by tlasadea** [comment]
As per ticket #8

**Comment by tlasadea** [comment]
@beccaklam copy [here](https://docs.google.com/document/d/1zq3TGpBGM25oLjFHD36emwlQHohAGVW0wr7Lb5X1oSc/edit), guide example [here](https://twitter.com/adyleefloyd/status/843804981065138177) (but obvi do whatever is best/in-line with other graphics)

**Comment by beccaklam** [comment]
@tlasadea https://redpen.io/uv76e7b1a4edb65678

**Comment by sabrinang** [comment]
## Post MozFest Documentation
This was posted on Oct 24 on mozillafestival twitter's account. This format fit better for twitter than the influencer infographic.
<img width="638" alt="image" src="https://user-images.githubusercontent.com/2492510/33221649-ee3d9cae-d105-11e7-8906-622dfbfc4410.png">
