### ISSUE TITLE
Printing Info Request - A2 size poster.

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/mozfest-design-2017#73]
Hello, I'd like to get some posters printed for the Web Literacy Space. 10 pieces at A3 size. Design is something like...

<img src="https://user-images.githubusercontent.com/25212/31402561-2ea9fefa-adab-11e7-8da3-b1d884c5cfba.png" width="350" />

Is it possible to add this to the print queue somehow? And if so...

* What are the deadlines?
* Any special requirements?
* How do we account for the costs associated with this?

It's for a partnership with the Mozilla Clubs program.

cc @marcwalsh - thanks for any info!

**Comment by marcwalsh** [comment]
Hey @flukeout - we'll print these onsite for you. 

Head to Level 4 on Friday and Ravensbourne students will be able to help you. :)

**Comment by flukeout** [comment]
Thanks very much @marcwalsh - I'll have the files ready to go.
