### ISSUE TITLE
Influencer Infographic

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/mozfest-design-2017#74]
Create a "guide to MozFest 2017" infographic that can be easily shared on social with influencers.

@edrushka @Saallen would be amazing if you could sense [check this content](https://docs.google.com/a/mozilla.com/document/d/1Nve4rAgxLejxZM2DIJBVeUHtcYX0QYNlev62UILKLsE/edit?usp=sharing) to ensure the messaging is on brand/appropriate. I pulled everything from MozillaFestival.com & the MozFest House deck.

Two questions for you two also: 1) when is MozFest House being announced? 2) Will there be a website/blog people can go to for more info?

Thanks!
@beccaklam once content is approved, you can start.

**Comment by Saallen** [comment]
Hello- loooks good to me
You can point ppl here https://mozillafestival.org/house

**Comment by edrushka** [comment]
Content looks good - I added one question in the doc. House has already been announced here: https://medium.com/mozilla-festival/three-days-just-isnt-enough-for-some-internet-health-enthusiasts-17a127f48200

**Comment by beccaklam** [comment]
@tlasadea https://redpen.io/p/vpe21e7ce4e8d2b8d7
Hey Temi, I didn't add the links in yet because I don't think we want to link to github tickets? I also don't have a link to where people can buy tickets.

**Comment by tlasadea** [comment]
@beccaklam yep we can link the sessions to the github tickets that's np, and the only link we need for MozFest House is where it says MozFest House in the heading "new for 2017 is mozfest house" (https://mozillafestival.org/house) and then for the tickets link at the bottom, it's here: (https://mozillafestival.org/tickets)

**Comment by beccaklam** [comment]
@tlasadea Updated the links. You'll need to share the pdf version for the links to work. Didn't have a link for the Decentralization talk! https://drive.google.com/a/mozilla.com/file/d/0BzuBOR2VJQqUUk4zWEZNeld6dTA/view?usp=sharing

**Comment by beccaklam** [comment]
@tlasadea Final link added! https://drive.google.com/open?id=0BzuBOR2VJQqUMW5qUDY5cHZsNVk

**Comment by edrushka** [comment]
Hi all - sorry to report that the youth session featured in this infographic has just pulled out of MozFest. Just an FYI.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

This was posted on Oct 24 on mozillafestival twitter's account. Nice use of photography in the background.
<img width="503" alt="image" src="https://user-images.githubusercontent.com/2492510/33221427-56bb3306-d104-11e7-93d6-b193c5392836.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/2492510/33221444-70526b18-d104-11e7-860e-983d109ac3d7.png">

Cropped versions in individual tweets
<img width="593" alt="screenshot 2017-11-24 11 08 50" src="https://user-images.githubusercontent.com/4515662/33221898-fc9e5002-d107-11e7-93f0-89e582d4f57a.png">
:
<img width="633" alt="screenshot 2017-11-24 11 06 30" src="https://user-images.githubusercontent.com/4515662/33221855-b3fd0a8c-d107-11e7-83ce-d472679cad1c.png">

**Comment by edrushka** [comment]
This asset was lovely!

Note if we create a similar graphic for 2018 that session titles change/merge in the final weeks/days before the festival. 

Also, total number of sessions changes because of emergent sessions
