### ISSUE TITLE
Gobo Design

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2017#75]
Ticket to discuss the gobo (projected logo) use on Level 4 wall. 

What lockup / logo do we want to appear on the wall?

**Comment by edrushka** [comment]
We can only use a single image, right? I guess just the straight up wordmark w/gear is best: 
<img width="352" alt="mozilla-festival_lockup-black" src="https://user-images.githubusercontent.com/4515662/31465520-0edfb6a8-ae89-11e7-9e91-922dec10ae9f.png">

**Comment by sabrinang** [comment]
Is this the same as https://github.com/MozillaFoundation/mozfest-design-2017/issues/11 or something else?

**Comment by marcwalsh** [comment]
@sabrinang - sorry it is. Closing this and lets continue on #11
