### ISSUE TITLE
Sign: Sponsor Banner

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#76]
As part of #2, we are making a banner to feature our seven sponsors near the entrance and registration. 

### Format
I'm looking at the expobanner format on Pixart printing: https://www.pixartprinting.co.uk/displays/banner-stands/expobanner-luxury-mono/

**Comment by sabrinang** [comment]
@marcwalsh Do you think the https://www.pixartprinting.co.uk/displays/banner-stands/expobanner-luxury-mono/ format is appropriate for this?

@edrushka Does the standing banner format work for this? Also, I referred to the email for the content but it seems out of date compared to the guide - see redpen: https://redpen.io/p/fa58a6fc4663ff848f

**Comment by marcwalsh** [comment]
@sabrinang Totally - an alternative can be this which is slightly cheaper if we want to avoid the roller banner. 

https://www.pixartprinting.co.uk/displays/banner-stands/expobanner-xplus/

**Comment by edrushka** [comment]
@jcbarajas two questions:
1) will this banner be big enough to meet our display requirements in the registration area: https://www.pixartprinting.co.uk/displays/banner-stands/expobanner-xplus/
2) Can we use the same layout as the festival guide (supporting partner alone on top, other partners 2 per row) or should we use the layout indicated in [this doc](https://docs.google.com/document/d/1unimp4LxiOa2tLOEUAFmWlLFktuNzoRYwUc9Sh_-Y_g/edit?userstoinvite=sabrina@mozillafoundation.org&ts=59deb1f5&actionButton=1)

**Comment by jcbarajas** [comment]
This banner looks big enough and should satisfy our sponsors. Go ahead and use the festival guide layout. However, please add language to the top that says: Thank you MozFest 2017 sponsors. This makes clear what it is.

**Comment by edrushka** [comment]
@sabrinang based on Juan's feedback I made some comments in the redpen.

**Comment by sabrinang** [comment]
@edrushka I updated copy and arrangement of logos to fit on the [expobanner-xplus banner](https://www.pixartprinting.co.uk/displays/banner-stands/expobanner-xplus/) format on redpen: https://redpen.io/p/fa58a6fc4663ff848f

Can you review content and give feedback on arrangement?

**Comment by edrushka** [comment]
R+ from Juan and I. Thank you!

**Comment by sabrinang** [comment]
@marcwalsh Print .pdf here: https://drive.google.com/open?id=0B4Q8pzCpDS_eLVdOVHo3ZTlHcDQ

**Comment by marcwalsh** [comment]
Sent for print!
