### ISSUE TITLE
Intentionally blank posters

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/mozfest-design-2017#77]
Poster with discreet text at top or bottom that says :“Give your eyes a break. This space is intentionally blank.”

Can have a subtle frame like the [sponsors page](https://redpen.io/bt2ec03711bd6da65d) or the [notes page](https://redpen.io/rtf10bebb997ec7c56) or just be blank except for the text.

**Comment by edrushka** [comment]
@sabrinang @marcwalsh I forgot to add this to the queue!

**Comment by sabrinang** [comment]
Sure, this is an interesting request... 
![blank 1](https://user-images.githubusercontent.com/2492510/31529400-e27424a4-af8d-11e7-8391-3312da63cab6.jpg)
![blank 2](https://user-images.githubusercontent.com/2492510/31529401-e292353e-af8d-11e7-8f0f-0adef8ad6b99.jpg)

**Comment by edrushka** [comment]
~~thanks! Parts of the images seem broken - possible to post on redpen?~~ I'm a dork :nerd_face: and didn't get this design joke until Sabrina pointed it out.

**Comment by sabrinang** [comment]
@edrushka 🤓 What dimensions were you thinking for these?

**Comment by edrushka** [comment]
Ideally A3s for us to post on walls in busy spaces, and A4s for people to individually post where they need.

**Comment by marcwalsh** [comment]
Top design - I will send templates

**Comment by marcwalsh** [comment]
Templates are below :) @sabrinang 

[A3-Pixart-Poster.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1396565/A3-Pixart-Poster.pdf)

[A4-Pixart-Poster.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1396566/A4-Pixart-Poster.pdf)

**Comment by sabrinang** [comment]
@edrushka I made the border go to the edge of the page itself in a pixelated style with larger text since it felt like it was getting lost:
![blank final 2x](https://user-images.githubusercontent.com/2492510/31866529-c0ce5f40-b735-11e7-82e4-4210a010ba22.jpg)

If this is good to go, A3 A4 print exports are here: https://drive.google.com/open?id=0B4Q8pzCpDS_edGYtc3NHR3Y1MlE
