### ISSUE TITLE
Print MoFo flyers for House

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mozfest-design-2017#78]
@marcwalsh - We have a small A5 flyer designed by @kristinashu that we would like at the House registration desk. Can you coordinate printing and delivery to @lucieclick?

 - Print pdf: [PulseMozFestPoster-A5.pdf](https://github.com/MozillaFoundation/mozfest-design-2017/files/1388375/PulseMozFestPoster-A5.pdf)

 - Quantity: 500

Note: we also want to put this up around Ravensbourne. Some on the wall, some in stacks by kiosk. We probably just need 200 there. Should I file a separate ticket for that?

**Comment by sabrinang** [comment]
is this on redpen? just a note you may want to lighten the line/concentrated waves on the right that cuts across the center it might print dark that distracts from the copy

**Comment by kristinashu** [comment]
Thanks @sabrinang! I've made the lines thinner and more transparent. I've updated the pdf above and here it is in [Redpen ](https://redpen.io/p/sob006295844fa5bdc).

**Comment by xmatthewx** [comment]
@marcwalsh – are you able to coordinate printing and delivery to @lucieclick?

**Comment by marcwalsh** [comment]
@xmatthewx - they'll be arriving on Monday! :)

**Comment by sabrinang** [comment]
## Post MozFest & House Documentation

Flyers were found at MozFest House and MozFest registration tables. They were also available at the pulse demo stand throughout the festival. It seemed like there was a huge quantity but we may not need so many or we can put them up as posters. Unsure how many flyers were taken in this format (I saw someone take photos of it though).  
![mozfest-house-29](https://user-images.githubusercontent.com/2492510/33044097-5c452616-cdfc-11e7-9bb6-996cb02b5097.jpg)
![mozfest-house-31](https://user-images.githubusercontent.com/2492510/33044103-5ee33908-cdfc-11e7-87ae-37d1fbd98bfe.jpg)
