### ISSUE TITLE
Swag: USB Flash Drive

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#79]
### Description:
USB flash drives will be available swag. This may be Youth Zone specific or MozFest wide @marcwalsh to clarify.

**Format**
This will be ordered from Flashbay http://www.flashbay.co.uk/usb-sticks/trix
<img width="755" alt="image" src="https://user-images.githubusercontent.com/2492510/31579329-dc83de3e-b0e8-11e7-958b-849510eb8845.png">

**Comment by sabrinang** [comment]
I have some design mockups on redpen: https://redpen.io/p/mc73c8144f089f01e5

@marcwalsh So far they are MozFest designs but let me know if they should be more Youth Zone branded

**Comment by marcwalsh** [comment]
@sabrinang - myself and @edrushka <3 the rainbow - lets go for it. :)

**Comment by sabrinang** [comment]
@marcwalsh .pdf / .svg files available here for print: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eWk9YVHQ1RV9iRTA?usp=sharing

**Comment by sabrinang** [comment]
squared usb flash drives are out of production so we are going with narrow design with just the [white gear logo](https://drive.google.com/file/d/0B4Q8pzCpDS_eYlJnVktNUVplVDA/view?usp=sharing)
<img width="240" alt="image" src="https://user-images.githubusercontent.com/2492510/31856696-5d92a1a2-b67c-11e7-89d7-5f9e2ccb0362.png">

**Comment by marcwalsh** [comment]
Sent for print - ETA: Friday pre-12
