### ISSUE TITLE
Elife Poster

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/mozfest-design-2017#80]
@sabrinang Please make a poster that says:

ELife Open Science Soapbox
[Elife's logo - same one that I emailed you]
12:30 - 1:45
Sunday 29th October
8th Floor Boardroom

please make A3 size and we'll print two copies, as stipulated in our contract w/ELife

**Comment by sabrinang** [comment]
@edrushka Please review content/design on redpen: https://redpen.io/p/de2a6d91bbe42c28f4
.pdf here: https://drive.google.com/open?id=0B4Q8pzCpDS_eeVZBaExDZ1M1N0E

@marcwalsh how much bleed or what template should I export this with?

**Comment by marcwalsh** [comment]
@sabrinang - Let's print these onsite so your standard 3mm bleed with crop marks is fine. :)

**Comment by edrushka** [comment]
R+ very nice!

**Comment by sabrinang** [comment]
@marcwalsh Ready for print
.pdf here: https://drive.google.com/open?id=0B4Q8pzCpDS_eeVZBaExDZ1M1N0E

**Comment by marcwalsh** [comment]
This was printed on-site! :)

**Comment by sabrinang** [comment]
## Post MozFest Documentation
A few eLife posters went up around the space:
![mozilla-festival-2017-239](https://user-images.githubusercontent.com/2492510/33043885-b59a2528-cdfb-11e7-9554-8cd0c3522b88.jpg)

eLife provided their own totem that looked great:
![20171027-mozfest-161 1](https://user-images.githubusercontent.com/2492510/33191231-07209e32-d06c-11e7-8f15-0e1bfe9f6ded.jpg)
