### ISSUE TITLE
Repro for Print - MozFest Wrangler 

### ISSUE THREAD

**Issue by xaviercooksonedwards** [MozillaFoundation/mozfest-design-2017#81]
Hi Sabrina, 

Please can you resize the attached PNG to the dimensions of 3x3inchs? And make it print ready for A4? We will be printing from our office printer. 

We need to print 40 of them so please can you line as many as you can on a A4 spread. 

Thanks!
Xavi
![wrangler](https://user-images.githubusercontent.com/32964344/31832702-e4c22408-b5bf-11e7-85fa-ee24d9c32184.png)

**Comment by xaviercooksonedwards** [comment]
Hi Sabrina, 

Please can you also do the same for the attached red version? 

Thanks!
Xavi
![wrangler red](https://user-images.githubusercontent.com/32964344/31861349-8d91df2e-b723-11e7-88f9-dbfdf2c71cac.jpg)

**Comment by sabrinang** [comment]
@xaviercooksonedwards You can find the A4 .pdf here: https://drive.google.com/open?id=0B4Q8pzCpDS_eVUZJaklJLXd0N2c 

Six 3"x3" squares can fit on a single A4 sheet. I included black, the red tone above and the red tone in the mozfest palette (just in case you need it). 

<img width="879" alt="image" src="https://user-images.githubusercontent.com/2492510/31867123-8aaf9cd6-b73e-11e7-9944-f679e7e772e8.png">

Let me know if you need any other colours, I wasn't sure if you needed these to correspond to the colours of the spaces or not or if the fabric square itself would be multi-coloured!

**Comment by xaviercooksonedwards** [comment]
Thank you! Looks great :)
