### ISSUE TITLE
[post-festival] MozEd logo

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/mozfest-design-2017#82]
Please design a simple MozEd logo, using MozFest style guide, for Su Adams' event later in November.

cc @EsmeSimcox @Saallen

**Comment by EsmeSimcox** [comment]
This is the logo at the moment: 
<img width="779" alt="screen shot 2017-10-23 at 16 43 25" src="https://user-images.githubusercontent.com/30292263/31898614-606b5ac2-b811-11e7-90f0-a9d365819562.png">

**Comment by sabrinang** [comment]
<img width="610" alt="screen shot 2017-11-03 at 11 30 54 am" src="https://user-images.githubusercontent.com/2492510/32390164-90fb6656-c08a-11e7-8156-e6333626ffe3.png">

I'm referring to https://mozilla.ninja/expression/ "Limited use lockup with secondary text" section. If this is loosely tied then you can just use Zilla Slab (bottom option).

@edrushka Any feedback or thoughts? I also don't have context how this is applied or used.

**Comment by EsmeSimcox** [comment]
These look amazing thank you!

**Comment by EsmeSimcox** [comment]
@sabrinang Are these ready to go?

**Comment by sabrinang** [comment]
@edrushka Flagging for review?

@EsmeSimcox If this is needed more urgently (incase I don't hear back from erika in time for this event), I'd go with the second option. When is this needed by or when is Su's event?

**Comment by EsmeSimcox** [comment]
@sabrinang Su's event is in 10 days, I will speak to Su this evening and see when the latest we can have it by. As I need to order banners for the event, which we would love to put the logo on!

**Comment by xmatthewx** [comment]
I think the bottom option works very well for this type of thing.

**Comment by sabrinang** [comment]
@EsmeSimcox Exports are here in google drive: https://drive.google.com/open?id=14Enobah3temLpx05xdEEmO6VJgY9Vxv9

**Comment by EsmeSimcox** [comment]
Great thank you @xmatthewx and @sabrinang for you help! I will send you photos of the logo at the venue after the event.

**Comment by sabrinang** [comment]
## Post MozEd Documentation

<img width="611" alt="image" src="https://user-images.githubusercontent.com/2492510/38895695-918da290-4245-11e8-857b-cb9dcd277855.png">

![](https://cdn-images-1.medium.com/max/2000/1*-CHcJRSkCxDIgysIl9QHMw.jpeg)

Esme's blog post here: https://medium.com/mozilla-festival/mozed-a-mozfest-fringe-event-bd62b9094adf
