### ISSUE TITLE
Level 4 Wall Wash (RGB)

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2017#83]
Hey @sabrinang 

Would you be able to give me an RGB value for the light wash on the rear wall of level 4 please?

**Comment by sabrinang** [comment]
## Post Mozfest Documentation

During MozFest, I chatted to the lighting designer Luke to set up the lights. The initial RGB values from the palette were a bit washed out so we adjust the values to produce the final product. There were 4 spot lights that could be customized so we created a gradient pink-puple-blue from left to right with them. 
![mozilla-festival-2017-306](https://user-images.githubusercontent.com/2492510/33043172-548f1e02-cdf9-11e7-9604-da002bb0c053.jpg)


The gear logo light can also be programmed to move. It can scale, rotate, go on paths etc. and ultimately we went for a very slow rotation similar to last year to not be too distracting. The gear is in cyan but often appears white in photos.
![mozfest-lighting](https://user-images.githubusercontent.com/2492510/33042747-c7360a4e-cdf7-11e7-8810-a52cf93ee7a0.gif)

These lights accepts values in RGB or CMY.
