### ISSUE TITLE
Title and end cards for D&D videos

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/mozfest-design-2017#87]
Need a branded title card for each D&D, and a single end card to use for all of them.

**Title cards should say:**
[speaker(s) name]
MozFest 2017
Dialogues and Debates
These [speaker profiles](https://redpen.io/p/afd81c048a44b1f919) are gorgeous - is it possible to "Dialogues and Debates"?

**Speakers** 
- Julia Angwin
- Ashley Black
- Mishi Choudhary
- Gillian Crampton Smith
- Emily Gorcenski & Sarah Jeong
- Alan Knott-Craig, Jr.
- Emily May
- Matt Mitchell
- Gisela Perez de Acha
- Nanjira Sambuli
- Anasuya Sengupta & Siko Bouterse
- Audrey Tang
- Ugo Vallauri
- Katherine Maher, Ryan Merkley & Mark Surman

**End card should say:**
MozFest
The world's leading festival for the open internet movement.
www.mozfest.org

**Specs**
1920x1080
PNG format

**Deadline**
Jan 19, 2017 if possible (@xmatthewx  to confirm after assigning)

**Comment by edrushka** [comment]
cc @Saallen @KevZawacki

**Comment by xmatthewx** [comment]
Thanks. I'm going to share a [project brief](https://docs.google.com/document/d/1_N2VanU6SSLNIBY3rIUdDhMcy4QUiAGkElyGZUA1uZM/edit#heading=h.jbsf2wnv5omm) so we can line this up with other projects in the queue.

**Comment by sabrinang** [comment]
@edrushka Please review this redpen: https://redpen.io/p/ve77caadc25f8d325f 
It contains the 14 speaker slides + 1 end card slide

**Comment by KevZawacki** [comment]
@sabrinang @edrushka These look great! No changes from me.

**Comment by edrushka** [comment]
These work for me. If you can export in PNG I will send to the video team. Thanks, Sabrina!

**Comment by sabrinang** [comment]
Thanks team! Here are the images exported to .png 1920 × 1080 format on gdrive: https://drive.google.com/open?id=1H3cc4VG1kwUOJV75so2Sjk9nAacgpvnr

**Comment by edrushka** [comment]
Oops! Forgot to include Nighat Dad in the original list. Can you please make one with her name?

**Comment by Saallen** [comment]
They look great - thanks @sabrinang 🌷

**Comment by sabrinang** [comment]
@edrushka Here is a slide for Nighat: https://drive.google.com/open?id=1RTJEkdon_H2nk8Gs3pZcGZP_KsM9EV-N (it is also included with the others in the PNGs folder)

**Comment by edrushka** [comment]
Thanks! I think this should do it for the slides, but I'll wait to close the ticket until I get the final ok from the video crew.

**Comment by sabrinang** [comment]
## Post Mozfest Documentation
These title & end cards are seen on the youtube (playlist [here](https://www.youtube.com/watch?v=atYKpi_74Ak&list=PLYiaJo7rYNXInD71OAShY4xfl6fhskoUV)). These are different than the live air mozilla slides and knowing it is used for Youtube now I can coordinate with whoever does the End screen/Annotations editing or leave generous space for our profile hover state and playlist thumbnail element. You can see how the type is obstructed below:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/2492510/38895149-12ba4e2e-4244-11e8-8b11-dccdd1dd6d14.png">
